// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * @category Primitive
 */
export type ConfigurationParameterType = "string" | "number" | "boolean" | "object" | "array";

/**
 * DEPRECATED
 * Should be removed when its unused
 *
 * @category Primitive
 */
export type ConfigurationTarget = "USER" | "WORKSPACE";
