// Generated by ts-to-zod
import { z } from "zod";

export const configurationParameterTypeSchema = z.union([
  z.literal("string"),
  z.literal("number"),
  z.literal("boolean"),
  z.literal("object"),
  z.literal("array"),
]);

export const configurationTargetSchema = z.union([z.literal("USER"), z.literal("WORKSPACE")]);
