// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import { JsonValue } from "@repo/moss-bindingutils";
import type { ConfigurationParameterType } from "./primitives";

/**
 * @category Type
 */
export type ConfigurationSchema = {
  id: string;
  parentId?: string;
  order?: bigint;
  name?: string;
  description?: string;
  parameters: Array<ParameterSchema>;
};

/**
 * @category Type
 */
export type ParameterSchema = {
  id: string;
  default?: JsonValue;
  typ: ConfigurationParameterType;
  description?: string;
  maximum?: bigint;
  minimum?: bigint;
  protected: boolean;
  order?: bigint;
  tags: Array<string>;
};
