// @ts-nocheck - File uses recursive schemas that may cause "Type instantiation is excessively deep" errors
// Generated by ts-to-zod
import { jsonValueSchema } from "@repo/moss-bindingutils";
import { z } from "zod";
import { configurationParameterTypeSchema } from "./primitives.zod";
export const parameterSchemaSchema = z.object({
  id: z.string(),
  default: jsonValueSchema.optional(),
  typ: configurationParameterTypeSchema,
  description: z.string().optional(),
  maximum: z.bigint().optional(),
  minimum: z.bigint().optional(),
  protected: z.boolean(),
  order: z.bigint().optional(),
  tags: z.array(z.string()),
});

export const configurationSchemaSchema = z.object({
  id: z.string(),
  parentId: z.string().optional(),
  order: z.bigint().optional(),
  name: z.string().optional(),
  description: z.string().optional(),
  parameters: z.array(parameterSchemaSchema),
});
