// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type VariableInfo = {
  name: string;
  globalValue: VariableValue;
  localValue: VariableValue;
  disabled: boolean;
  kind: VariableKind;
  order: number | null;
  desc: string | null;
};

export type VariableKind = "secret" | "default";

export type VariableValue = string | number | boolean | null;
