// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ConfigurationParameterType = "string" | "number" | "boolean" | "object" | "array";

export type ConfigurationTarget = "PROFILE" | "WORKSPACE";
