// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import { JsonValue } from "@repo/moss-bindingutils";
import type { LogLevel } from "./primitives";

/**
 * @category Event
 */
export type OnDidAddExtension = { id: string };

/**
 * @category Event
 */
export type OnDidAppendLogEntry = {
  id: string;
  /**
   * A timestamp string, such as "2025-06-06T19:26:39.084+0300"
   */
  timestamp: string;
  level: LogLevel;
  resource?: string;
  message: string;
};

/**
 * @category Event
 */
export type OnDidChangeConfiguration = { affected_keys: Array<string>; changes: { [key: string]: JsonValue } };
