// Generated by ts-to-zod
import { z } from "zod";
import { logLevelSchema } from "./primitives.zod";

export const onDidAddExtensionSchema = z.object({
  id: z.string(),
});
export const onDidAppendLogEntrySchema = z.object({
  id: z.string(),
  timestamp: z.string(),
  level: logLevelSchema,
  resource: z.string().optional(),
  message: z.string(),
});
