// Generated by ts-to-zod
import { z } from "zod";
import { logLevelSchema } from "./primitives.zod";
import { logDateSchema, logEntryInfoSchema, logItemSourceInfoSchema } from "./types.zod";

export const batchDeleteLogInputSchema = z.object({
  ids: z.array(z.string()),
});
export const batchDeleteLogOutputSchema = z.object({
  deletedEntries: z.array(logItemSourceInfoSchema),
});

export const listLogsInputSchema = z.object({
  dates: z.array(logDateSchema),
  levels: z.array(logLevelSchema),
  resource: z.string().optional(),
});

export const listLogsOutputSchema = z.object({
  contents: z.array(logEntryInfoSchema),
});
