// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LogLevel } from "./primitives";
import type { LogDate, LogEntryInfo, LogItemSourceInfo } from "./types";

/**
 * @category Operation
 */
export type BatchDeleteLogInput = { ids: Array<string> };

/**
 * @category Operation
 */
export type BatchDeleteLogOutput = { deletedEntries: Array<LogItemSourceInfo> };

/**
 * @category Operation
 */
export type ListLogsInput = { dates: Array<LogDate>; levels: Array<LogLevel>; resource?: string };

/**
 * @category Operation
 */
export type ListLogsOutput = { contents: Array<LogEntryInfo> };
