// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import { ConfigurationTarget, ProfileInfo } from "@repo/base";
import { JsonValue } from "@repo/moss-bindingutils";
import { LanguageInfo } from "@repo/moss-language";
import type { LogLevel } from "./primitives";
import type {
  AddAccountParams,
  Configuration,
  LogDate,
  LogEntryInfo,
  LogItemSourceInfo,
  UpdateAccountParams,
  WorkspaceInfo,
} from "./types";

/**
 * @category Operation
 */
export type BatchDeleteLogInput = { ids: Array<string> };

/**
 * @category Operation
 */
export type BatchDeleteLogOutput = { deletedEntries: Array<LogItemSourceInfo> };

/**
 * @category Operation
 */
export type CloseWorkspaceInput = {
  /**
   * The workspace id is required to ensure the close function
   * is only called when a workspace is open.
   */
  id: string;
};

/**
 * @category Operation
 */
export type CloseWorkspaceOutput = {
  /**
   * The id of the workspace that was closed.
   */
  id: string;
};

/**
 * DEPRECATED
 * @category Operation
 */
export type CreateProfileInput = { name: string; isDefault?: boolean };

/**
 * DEPRECATED
 * @category Operation
 */
export type CreateProfileOutput = { profile_id: string };

/**
 * DEPRECATED
 * @category Operation
 */
export type DescribeAppOutput = {
  /**
   * The id of the workspace that is currently opened.
   */
  workspace?: WorkspaceInfo;
  /**
   * The id of the profile that is currently active.
   */
  profile?: ProfileInfo;
  configuration: Configuration;
};

/**
 * @category Operation
 */
export type DescribeWorkbenchStateOutput = { prevWorkspaceId?: string };

/**
 * @category Operation
 */
export type GetTranslationNamespaceInput = { language: string; namespace: string };

/**
 * @category Operation
 */
export type GetTranslationNamespaceOutput = { contents: JsonValue };

/**
 * @category Operation
 */
export type ListLanguagesOutput = LanguageInfo[];

/**
 * @category Operation
 */
export type ListLogsInput = { dates: Array<LogDate>; levels: Array<LogLevel>; resource?: string };

/**
 * @category Operation
 */
export type ListLogsOutput = { contents: Array<LogEntryInfo> };

/**
 * @category Operation
 */
export type OpenWorkspaceInput = { id: string };

/**
 * DEPRECATED
 * @category Operation
 */
export type OpenWorkspaceOutput = { id: string };

/**
 * DEPRECATED
 * @category Operation
 */
export type UpdateConfigurationInput = { key: string; value: JsonValue; target: ConfigurationTarget };

/**
 * DEPRECATED
 * @category Operation
 */
export type UpdateProfileInput = {
  accountsToAdd: Array<AddAccountParams>;
  accountsToRemove: Array<string>;
  accountsToUpdate: Array<UpdateAccountParams>;
};

/**
 * DEPRECATED
 * @category Operation
 */
export type UpdateProfileOutput = {
  added_accounts: Array<string>;
  removed_accounts: Array<string>;
  updated_accounts: Array<string>;
};
