// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import { AccountKind, ConfigurationTarget } from "@repo/base";
import { JsonValue } from "@repo/moss-bindingutils";
import type { LogLevel } from "./primitives";

/**
 * @category Type
 */
export type AddAccountParams = {
  host: string;
  kind: AccountKind;
  /**
   * If a PAT is not provided, we will use OAuth
   */
  pat?: string;
};

/**
 * DEPRECATED
 * @category Type
 */
export type Configuration = { keys: Array<string>; contents: { [key: string]: JsonValue } };

/**
 * @category Type
 */
export type LogDate = { year: number; month: number; day: number };

/**
 * @category Type
 */
export type LogEntryInfo = {
  id: string;
  /**
   * A timestamp string, such as "2025-06-06T19:26:39.084+0300"
   */
  timestamp: string;
  level: LogLevel;
  resource?: string;
  message: string;
};

/**
 * @category Type
 */
export type LogItemSourceInfo = { id: string };

/**
 * @category Type
 */
export type UpdateAccountParams = { id: string; pat?: string };

/**
 * DEPRECATED
 * @category Type
 */
export type UpdateConfigurationParams = { key: string; value: JsonValue; target: ConfigurationTarget };

/**
 * @category Type
 */
export type WorkspaceInfo = { id: string; name: string; lastOpenedAt?: bigint };
