// @ts-nocheck - File uses recursive schemas that may cause "Type instantiation is excessively deep" errors
// Generated by ts-to-zod
import { accountKindSchema, configurationTargetSchema } from "@repo/base";
import { jsonValueSchema } from "@repo/moss-bindingutils";
import { z } from "zod";
import { logLevelSchema } from "./primitives.zod";

export const logDateSchema = z.object({
  year: z.number(),
  month: z.number(),
  day: z.number(),
});

export const logItemSourceInfoSchema = z.object({
  id: z.string(),
});

export const updateAccountParamsSchema = z.object({
  id: z.string(),
  pat: z.string().optional(),
});
export const addAccountParamsSchema = z.object({
  host: z.string(),
  kind: accountKindSchema,
  pat: z.string().optional(),
});

export const configurationSchema = z.object({
  keys: z.array(z.string()),
  contents: z.record(z.string(), jsonValueSchema),
});

export const logEntryInfoSchema = z.object({
  id: z.string(),
  timestamp: z.string(),
  level: logLevelSchema,
  resource: z.string().optional(),
  message: z.string(),
});

export const updateConfigurationParamsSchema = z.object({
  key: z.string(),
  value: jsonValueSchema,
  target: configurationTargetSchema,
});
