// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LogLevel } from "./primitives";

/**
 * @category Type
 */
export type LogDate = { year: number; month: number; day: number };

/**
 * @category Type
 */
export type LogEntryInfo = {
  id: string;
  /**
   * A timestamp string, such as "2025-06-06T19:26:39.084+0300"
   */
  timestamp: string;
  level: LogLevel;
  resource?: string;
  message: string;
};

/**
 * @category Type
 */
export type LogItemSourceInfo = { id: string };
