// Generated by ts-to-zod
import { z } from "zod";
import { logLevelSchema } from "./primitives.zod";

export const logDateSchema = z.object({
  year: z.number(),
  month: z.number(),
  day: z.number(),
});

export const logItemSourceInfoSchema = z.object({
  id: z.string(),
});
export const logEntryInfoSchema = z.object({
  id: z.string(),
  timestamp: z.string(),
  level: logLevelSchema,
  resource: z.string().optional(),
  message: z.string(),
});
