// Generated by ts-to-zod
import { z } from "zod";
import { branchInfoSchema } from "./types.zod";

export const streamEnvironmentsEventSchema = z.object({
  id: z.string(),
  collectionId: z.string().optional(),
  name: z.string(),
  order: z.number().optional(),
  totalVariables: z.number(),
});
export const streamCollectionsEventSchema = z.object({
  id: z.string(),
  name: z.string(),
  order: z.number().optional(),
  expanded: z.boolean(),
  repository: z.string().optional(),
  branch: branchInfoSchema.optional(),
  iconPath: z.string().optional(),
});
