// Generated by ts-to-zod
import { z } from "zod";

export const streamCollectionsEventSchema = z.object({
  id: z.string(),
  name: z.string(),
  order: z.number().nullable(),
});

export const streamEnvironmentsEventSchema = z.object({
  id: z.string(),
  collectionId: z.string().optional(),
  name: z.string(),
  order: z.number().optional(),
});
