// Generated by ts-to-zod
import { z } from "zod";
import { contributorSchema, repositoryInfoSchema } from "./types.zod";

export const streamEnvironmentsEventSchema = z.object({
  id: z.string(),
  collectionId: z.string().optional(),
  name: z.string(),
  order: z.number().optional(),
  expanded: z.boolean(),
});
export const streamCollectionsEventSchema = z.object({
  id: z.string(),
  name: z.string(),
  order: z.number().optional(),
  expanded: z.boolean(),
  repository: z.string().optional(),
  repositoryInfo: repositoryInfoSchema.optional(),
  contributors: z.array(contributorSchema),
  picturePath: z.string().optional(),
});
