// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BranchInfo, Contributor, RepositoryInfo } from "./types";

/**
 * @category Event
 */
export type StreamCollectionsEvent = {
  id: string;
  name: string;
  order?: number;
  expanded: boolean;
  repository?: string;
  repositoryInfo?: RepositoryInfo;
  contributors: Array<Contributor>;
  branchInfo?: BranchInfo;
  picturePath?: string;
};

/**
 * @category Event
 */
export type StreamEnvironmentsEvent = {
  id: string;
  /**
   * The id of the collection that the environment belongs to.
   * If the environment is global, this will be `None`.
   */
  collectionId?: string;
  name: string;
  order?: number;
  expanded: boolean;
};
