// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type StreamCollectionsEvent = {
  id: string;
  name: string;
  repository?: string;
  order?: number;
  picturePath?: string;
};

export type StreamEnvironmentsEvent = {
  id: string;
  /**
   * The id of the collection that the environment belongs to.
   * If the environment is global, this will be `None`.
   */
  collectionId?: string;
  name: string;
  order?: number;
};
