// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import { VariableInfo } from "@repo/moss-environment";
import type { ChangePath, ChangeString } from "./primitives";
import type { ActivitybarPartStateInfo, EditorPartStateInfo, PanelPartStateInfo, SidebarPartStateInfo } from "./types";

/**
 * @category Operation
 */
export type CreateCollectionInput = {
  name: string;
  order: number;
  externalPath?: string;
  repo?: string;
  iconPath?: string;
};

/**
 * @category Operation
 */
export type CreateCollectionOutput = { id: string; name: string; order?: number; expanded: boolean; iconPath?: string };

/**
 * @category Operation
 */
export type DeleteCollectionInput = { id: string };

/**
 * @category Operation
 */
export type DeleteCollectionOutput = { id: string };

/**
 * @category Operation
 */
export type DescribeEnvironmentInput = { id: string };

/**
 * @category Operation
 */
export type DescribeEnvironmentOutput = { variables: VariableInfo };

/**
 * @category Operation
 */
export type DescribeStateOutput = {
  editor?: EditorPartStateInfo;
  sidebar?: SidebarPartStateInfo;
  panel?: PanelPartStateInfo;
  activitybar?: ActivitybarPartStateInfo;
};

/**
 * @category Operation
 */
export type StreamCollectionsOutput = {};

/**
 * @category Operation
 */
export type UpdateCollectionInput = {
  id: string;
  name?: string;
  repository?: ChangeString;
  iconPath?: ChangePath;
  order?: number;
  pinned?: boolean;
  expanded?: boolean;
};

/**
 * @category Operation
 */
export type UpdateCollectionOutput = { id: string };

/**
 * @category Operation
 */
export type UpdateStateInput =
  | { "updateEditorPartState": EditorPartStateInfo }
  | { "updateSidebarPartState": SidebarPartStateInfo }
  | { "updatePanelPartState": PanelPartStateInfo }
  | { "updateActivitybarPartState": ActivitybarPartStateInfo };
