// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import { VariableInfo } from "@repo/moss-environment";
import type { CollectionInfo, EditorPartState, EnvironmentInfo, PanelPartState, SidebarPartState } from "./types";

export type CreateCollectionInput = { name: string; order?: number; externalPath?: string };

export type CreateCollectionOutput = { id: string };

export type DeleteCollectionInput = { id: string };

export type DeleteCollectionOutput = { id: string };

export type DescribeEnvironmentInput = { id: string };

export type DescribeEnvironmentOutput = { variables: VariableInfo };

export type DescribeStateOutput = { editor?: EditorPartState; sidebar?: SidebarPartState; panel?: PanelPartState };

export type DescribeWorkspaceOutput = { collections: Array<CollectionInfo>; environments: Array<EnvironmentInfo> };

export type UpdateCollectionEntryInput = { id: string; newName: string | null; order?: number; pinned?: boolean };

export type UpdateCollectionEntryOutput = { id: string };

export type UpdateStateInput =
  | { "updateEditorPartState": EditorPartState }
  | { "updateSidebarPartState": SidebarPartState }
  | { "updatePanelPartState": PanelPartState };
