// Generated by ts-to-zod
import { variableInfoSchema } from "@repo/base";
import { changeStringSchema } from "@repo/moss-bindingutils";
import { z } from "zod";
import {
  addVariableParamsSchema,
  entryChangeSchema,
  environmentGroupSchema,
  updateEnvironmentGroupParamsSchema,
  updateEnvironmentParamsSchema,
  updateVariableParamsSchema,
} from "./types.zod";

export const activateEnvironmentInputSchema = z.object({
  environmentId: z.string(),
});

export const activateEnvironmentOutputSchema = z.object({
  environmentId: z.string(),
});

export const batchUpdateEnvironmentOutputSchema = z.object({
  ids: z.array(z.string()),
});

export const createEnvironmentOutputSchema = z.object({
  id: z.string(),
  projectId: z.string().optional(),
  name: z.string(),
  order: z.number().optional(),
  color: z.string().optional(),
});

export const deleteEnvironmentInputSchema = z.object({
  id: z.string(),
});

export const deleteEnvironmentOutputSchema = z.object({
  id: z.string(),
});

export const describeEnvironmentInputSchema = z.object({
  id: z.string(),
});

export const updateEnvironmentGroupInputSchema = z.object({
  projectId: z.string(),
  expanded: z.boolean().optional(),
  order: z.number().optional(),
});

export const updateEnvironmentOutputSchema = z.object({
  id: z.string(),
});
export const batchUpdateEnvironmentGroupInputSchema = z.object({
  items: z.array(updateEnvironmentGroupParamsSchema),
});

export const batchUpdateEnvironmentInputSchema = z.object({
  items: z.array(updateEnvironmentParamsSchema),
});

export const createEnvironmentInputSchema = z.object({
  projectId: z.string().optional(),
  name: z.string(),
  order: z.number(),
  color: z.string().optional(),
  variables: z.array(addVariableParamsSchema),
});

export const describeEnvironmentOutputSchema = z.object({
  variables: variableInfoSchema,
});

export const listChangesOutputSchema = z.object({
  changes: z.array(entryChangeSchema),
});

export const streamEnvironmentsOutputSchema = z.object({
  groups: z.array(environmentGroupSchema),
});

export const updateEnvironmentInputSchema = z.object({
  id: z.string(),
  name: z.string().optional(),
  order: z.number().optional(),
  color: changeStringSchema.optional(),
  expanded: z.boolean().optional(),
  varsToAdd: z.array(addVariableParamsSchema),
  varsToUpdate: z.array(updateVariableParamsSchema),
  varsToDelete: z.array(z.string()),
});
