// Generated by ts-to-zod
import { variableInfoSchema } from "@repo/moss-environment";
import { z } from "zod";
import {
  activitybarPartStateInfoSchema,
  collectionInfoSchema,
  editorPartStateInfoSchema,
  environmentInfoSchema,
  panelPartStateInfoSchema,
  sidebarPartStateInfoSchema,
} from "./types.zod";

export const createCollectionInputSchema = z.object({
  name: z.string(),
  order: z.number().optional(),
  externalPath: z.string().optional(),
});

export const createCollectionOutputSchema = z.object({
  id: z.string(),
});

export const deleteCollectionInputSchema = z.object({
  id: z.string(),
});

export const deleteCollectionOutputSchema = z.object({
  id: z.string(),
});

export const describeEnvironmentInputSchema = z.object({
  id: z.string(),
});

export const updateCollectionInputSchema = z.object({
  id: z.string(),
  newName: z.string().nullable(),
  order: z.number().optional(),
  pinned: z.boolean().optional(),
});

export const updateCollectionOutputSchema = z.object({
  id: z.string(),
});
export const describeEnvironmentOutputSchema = z.object({
  variables: variableInfoSchema,
});

export const describeStateOutputSchema = z.object({
  editor: editorPartStateInfoSchema.optional(),
  sidebar: sidebarPartStateInfoSchema.optional(),
  panel: panelPartStateInfoSchema.optional(),
  activitybar: activitybarPartStateInfoSchema.optional(),
});

export const describeWorkspaceOutputSchema = z.object({
  collections: z.array(collectionInfoSchema),
  environments: z.array(environmentInfoSchema),
});

export const updateStateInputSchema = z.union([
  z.object({
    "updateEditorPartState": editorPartStateInfoSchema,
  }),
  z.object({
    "updateSidebarPartState": sidebarPartStateInfoSchema,
  }),
  z.object({
    "updatePanelPartState": panelPartStateInfoSchema,
  }),
  z.object({
    "updateActivitybarPartState": activitybarPartStateInfoSchema,
  }),
]);
