// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import { ChangePath, ChangeString } from "@repo/moss-bindingutils";
import type {
  AddVariableParams,
  Contributor,
  CreateProjectGitParams,
  EntryChange,
  EnvironmentGroup,
  ImportProjectSource,
  UpdateEnvironmentGroupParams,
  UpdateEnvironmentParams,
  UpdateProjectParams,
  UpdateVariableParams,
  VariableInfo,
  VcsInfo,
} from "./types";

export type ActivateEnvironmentInput = { environmentId: string };

export type ActivateEnvironmentOutput = { environmentId: string };

/**
 * @category Operation
 */
export type ArchiveProjectInput = { id: string };

/**
 * @category Operation
 */
export type ArchiveProjectOutput = { id: string };

/**
 * @category Operation
 */
export type BatchUpdateEnvironmentGroupInput = { items: Array<UpdateEnvironmentGroupParams> };

/**
 * @category Operation
 */
export type BatchUpdateEnvironmentInput = { items: Array<UpdateEnvironmentParams> };

/**
 * @category Operation
 */
export type BatchUpdateEnvironmentOutput = { ids: Array<string> };

/**
 * @category Operation
 */
export type BatchUpdateProjectInput = { items: Array<UpdateProjectParams> };

/**
 * @category Operation
 */
export type BatchUpdateProjectOutput = { ids: Array<string> };

/**
 * @category Operation
 */
export type CreateEnvironmentInput = {
  projectId?: string;
  name: string;
  order: number;
  color?: string;
  variables: Array<AddVariableParams>;
};

/**
 * @category Operation
 */
export type CreateEnvironmentOutput = { id: string; projectId?: string; name: string; order?: number; color?: string };

/**
 * @category Operation
 */
export type CreateProjectInput = {
  name: string;
  order: number;
  externalPath?: string;
  gitParams?: CreateProjectGitParams;
  iconPath?: string;
};

/**
 * @category Operation
 */
export type CreateProjectOutput = { id: string; name: string; order?: number; expanded: boolean; iconPath?: string };

/**
 * @category Operation
 */
export type DeleteEnvironmentInput = { id: string };

/**
 * @category Operation
 */
export type DeleteEnvironmentOutput = { id: string };

/**
 * @category Operation
 */
export type DeleteProjectInput = { id: string };

/**
 * @category Operation
 */
export type DeleteProjectOutput = { id: string };

/**
 * @category Operation
 */
export type DescribeEnvironmentInput = { id: string };

/**
 * @category Operation
 */
export type DescribeEnvironmentOutput = { variables: VariableInfo };

/**
 * @category Operation
 */
export type DescribeProjectInput = { id: string };

/**
 * @category Operation
 */
export type DescribeProjectOutput = {
  name: string;
  vcs?: VcsInfo;
  contributors: Array<Contributor>;
  createdAt: string;
};

/**
 * @category Operation
 */
export type ExportProjectInput = {
  id: string;
  /**
   * Path to the folder containing the output archive file
   */
  destination: string;
};

/**
 * @category Operation
 */
export type ExportProjectOutput = { archivePath: string };

/**
 * @category Operation
 */
export type ImportProjectInput = { name: string; order: number; source: ImportProjectSource; iconPath?: string };

/**
 * @category Operation
 */
export type ImportProjectOutput = { id: string; name: string; order?: number; expanded: boolean; iconPath?: string };

/**
 * @category Operation
 */
export type ListChangesOutput = { changes: Array<EntryChange> };

/**
 * @category Operation
 */
export type StreamEnvironmentsOutput = { groups: Array<EnvironmentGroup> };

/**
 * @category Operation
 */
export type StreamProjectsOutput = {};

/**
 * @category Operation
 */
export type UnarchiveProjectInput = { id: string };

/**
 * @category Operation
 */
export type UnarchiveProjectOutput = { id: string };

/**
 * @category Operation
 */
export type UpdateEnvironmentGroupInput = { projectId: string; expanded?: boolean; order?: number };

/**
 * @category Operation
 */
export type UpdateEnvironmentInput = {
  id: string;
  name?: string;
  order?: number;
  color?: ChangeString;
  expanded?: boolean;
  varsToAdd: Array<AddVariableParams>;
  varsToUpdate: Array<UpdateVariableParams>;
  varsToDelete: Array<string>;
};

/**
 * @category Operation
 */
export type UpdateEnvironmentOutput = { id: string };

/**
 * @category Operation
 */
export type UpdateProjectInput = {
  id: string;
  name?: string;
  repository?: ChangeString;
  iconPath?: ChangePath;
  order?: number;
  expanded?: boolean;
};

/**
 * @category Operation
 */
export type UpdateProjectOutput = { id: string };
