// Generated by ts-to-zod
import { z } from "zod";

export const activitybarPositionSchema = z.union([
  z.literal("DEFAULT"),
  z.literal("TOP"),
  z.literal("BOTTOM"),
  z.literal("HIDDEN"),
]);

export const changeCollectionIdSchema = z.union([
  z.object({
    "UPDATE": z.string(),
  }),
  z.literal("REMOVE"),
]);

export const editorGridOrientationSchema = z.union([z.literal("HORIZONTAL"), z.literal("VERTICAL")]);

export const panelRendererSchema = z.union([z.literal("onlyWhenVisible"), z.literal("always")]);

export const sidebarPositionSchema = z.union([z.literal("LEFT"), z.literal("RIGHT")]);
