// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ActivitybarPosition = "DEFAULT" | "TOP" | "BOTTOM" | "HIDDEN";

export type EditorGridOrientation = "HORIZONTAL" | "VERTICAL";

export type PanelRenderer = "onlyWhenVisible" | "always";

export type SidebarPosition = "LEFT" | "RIGHT";
