// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * @category Primitive
 */
export type ActivitybarPosition = "DEFAULT" | "TOP" | "BOTTOM" | "HIDDEN";

/**
 * @category Primitive
 */
export type ChangePath = { "UPDATE": string } | "REMOVE";

/**
 * @category Primitive
 */
export type ChangeString = { "UPDATE": string } | "REMOVE";

/**
 * @category Primitive
 */
export type EditorGridOrientation = "HORIZONTAL" | "VERTICAL";

/**
 * @category Primitive
 */
export type PanelRenderer = "onlyWhenVisible" | "always";

/**
 * @category Primitive
 */
export type SidebarPosition = "LEFT" | "RIGHT";
