// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

import { JsonValue } from "@repo/bindings-utils";

/**
 * @category Primitive
 */
export type ActivitybarPosition = "DEFAULT" | "TOP" | "BOTTOM" | "HIDDEN";

export type ChangeCollectionId = { "UPDATE": string } | "REMOVE";

export type ChangeJsonValue = { "UPDATE": JsonValue } | "REMOVE";

/**
 * @category Primitive
 */
export type ChangePath = { "UPDATE": string } | "REMOVE";

/**
 * @category Primitive
 */
export type ChangeString = { "UPDATE": string } | "REMOVE";

/**
 * @category Primitive
 */
export type EditorGridOrientation = "HORIZONTAL" | "VERTICAL";

/**
 * @category Primitive
 */
export type PanelRenderer = "onlyWhenVisible" | "always";

/**
 * @category Primitive
 */
export type SidebarPosition = "LEFT" | "RIGHT";
