// @ts-nocheck - File uses recursive schemas that may cause "Type instantiation is excessively deep" errors
// Generated by ts-to-zod
import { changeJsonValueSchema, changeStringSchema, jsonValueSchema } from "@repo/moss-bindingutils";
import { fileStatusSchema } from "@repo/moss-git";
import { z } from "zod";

export const variableOptionsSchema = z.object({
  disabled: z.boolean(),
});

export const branchInfoSchema = z.object({
  name: z.string(),
  ahead: z.number().optional(),
  behind: z.number().optional(),
});

export const environmentGroupSchema = z.object({
  projectId: z.string(),
  expanded: z.boolean(),
  order: z.number().optional(),
});

export const updateEnvironmentGroupParamsSchema = z.object({
  projectId: z.string(),
  expanded: z.boolean().optional(),
  order: z.number().optional(),
});
export const addVariableParamsSchema = z.object({
  name: z.string(),
  globalValue: jsonValueSchema,
  localValue: jsonValueSchema,
  order: z.number(),
  desc: z.string().optional(),
  options: variableOptionsSchema,
});

export const entryChangeSchema = z.object({
  projectId: z.string(),
  path: z.string(),
  status: fileStatusSchema,
});

export const updateVariableParamsSchema = z.object({
  id: z.string(),
  name: z.string().optional(),
  globalValue: changeJsonValueSchema.optional(),
  localValue: changeJsonValueSchema.optional(),
  order: z.number().optional(),
  desc: changeStringSchema.optional(),
  options: variableOptionsSchema.optional(),
});

export const updateEnvironmentParamsSchema = z.object({
  id: z.string(),
  name: z.string().optional(),
  order: z.number().optional(),
  color: changeStringSchema.optional(),
  expanded: z.boolean().optional(),
  varsToAdd: z.array(addVariableParamsSchema),
  varsToUpdate: z.array(updateVariableParamsSchema),
  varsToDelete: z.array(z.string()),
});
