// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

import { FileStatus } from "@repo/moss-git";

export type EntryChange = { projectId: string; path: string; status: FileStatus };
