// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

import { ChangeJsonValue, ChangeString, JsonValue } from "@repo/moss-bindingutils";
import { FileStatus } from "@repo/moss-git";

/**
 * @category Type
 */
export type AddVariableParams = {
  name: string;
  globalValue: JsonValue;
  localValue: JsonValue;
  order: number;
  desc?: string;
  options: VariableOptions;
};

/**
 * @category Type
 */
export type BranchInfo = { name: string; ahead?: number; behind?: number };

export type EntryChange = { projectId: string; path: string; status: FileStatus };

/**
 * @category Type
 */
export type EnvironmentGroup = { projectId: string; expanded: boolean; order?: number };

/**
 * @category Type
 */
export type UpdateEnvironmentGroupParams = { projectId: string; expanded?: boolean; order?: number };

/**
 * @category Type
 */
export type UpdateEnvironmentParams = {
  id: string;
  name?: string;
  order?: number;
  color?: ChangeString;
  expanded?: boolean;
  varsToAdd: Array<AddVariableParams>;
  varsToUpdate: Array<UpdateVariableParams>;
  varsToDelete: Array<string>;
};

/**
 * @category Type
 */
export type UpdateVariableParams = {
  id: string;
  name?: string;
  globalValue?: ChangeJsonValue;
  localValue?: ChangeJsonValue;
  order?: number;
  desc?: ChangeString;
  options?: VariableOptions;
};

/**
 * @category Type
 */
export type VariableOptions = { disabled: boolean };
