// Generated by ts-to-zod
import { z } from "zod";

export const accountAuthMethodKindSchema = z.union([z.literal("OAUTH"), z.literal("PAT")]);

export const accountKindSchema = z.union([z.literal("GITHUB"), z.literal("GITLAB")]);
