// @ts-nocheck - File uses recursive schemas that may cause "Type instantiation is excessively deep" errors
// Generated by ts-to-zod
import { jsonValueSchema } from "@repo/moss-bindingutils";
import { z } from "zod";
import { optionalValueSchema, storageScopeSchema } from "./primitives.zod";

export const batchPutItemOutputSchema = z.record(z.string(), z.never());

export const putItemOutputSchema = z.record(z.string(), z.never());
export const batchGetItemByPrefixInputSchema = z.object({
  scope: storageScopeSchema,
  prefix: z.string(),
});

export const batchGetItemByPrefixOutputSchema = z.object({
  scope: storageScopeSchema,
  items: z.record(z.string(), jsonValueSchema),
});

export const batchGetItemInputSchema = z.object({
  scope: storageScopeSchema,
  keys: z.array(z.string()),
});

export const batchGetItemOutputSchema = z.object({
  scope: storageScopeSchema,
  items: z.record(z.string(), jsonValueSchema.nullable()),
});

export const batchPutItemInputSchema = z.object({
  scope: storageScopeSchema,
  items: z.record(z.string(), jsonValueSchema),
});

export const batchRemoveItemByPrefixInputSchema = z.object({
  scope: storageScopeSchema,
  prefix: z.string(),
});

export const batchRemoveItemByPrefixOutputSchema = z.object({
  scope: storageScopeSchema,
  items: z.record(z.string(), jsonValueSchema),
});

export const batchRemoveItemInputSchema = z.object({
  scope: storageScopeSchema,
  keys: z.array(z.string()),
});

export const batchRemoveItemOutputSchema = z.object({
  scope: storageScopeSchema,
  items: z.record(z.string(), jsonValueSchema.nullable()),
});

export const getItemInputSchema = z.object({
  key: z.string(),
  scope: storageScopeSchema,
});

export const getItemOutputSchema = z.object({
  key: z.string(),
  value: optionalValueSchema,
  scope: storageScopeSchema,
});

export const putItemInputSchema = z.object({
  key: z.string(),
  scope: storageScopeSchema,
  value: jsonValueSchema,
});

export const removeItemInputSchema = z.object({
  key: z.string(),
  scope: storageScopeSchema,
});

export const removeItemOutputSchema = z.object({
  scope: storageScopeSchema,
  value: jsonValueSchema,
});
