// Generated by ts-to-zod
import { jsonValueSchema } from "@repo/moss-bindingutils";
import { z } from "zod";
import { scopeSchema } from "./primitives.zod";
export const getItemInputSchema = z.object({
  key: z.string(),
  scope: scopeSchema,
});

export const getItemOutputSchema = z.object({
  key: z.string(),
  value: jsonValueSchema,
  scope: scopeSchema,
});
