// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import { JsonValue } from "@repo/moss-bindingutils";
import type { OptionalValue, StorageScope } from "./primitives";

/**
 * @category Operation
 */
export type BatchGetItemByPrefixInput = { scope: StorageScope; prefix: string };

export type BatchGetItemByPrefixOutput = { scope: StorageScope; items: { [key: string]: JsonValue } };

/**
 * @category Operation
 */
export type BatchGetItemInput = { scope: StorageScope; keys: Array<string> };

/**
 * @category Operation
 */
export type BatchGetItemOutput = { scope: StorageScope; items: { [key: string]: JsonValue | null } };

/**
 * @category Operation
 */
export type BatchPutItemInput = { scope: StorageScope; items: { [key: string]: JsonValue } };

/**
 * @category Operation
 */
export type BatchPutItemOutput = Record<string, never>;

/**
 * @category Operation
 */
export type BatchRemoveItemByPrefixInput = { scope: StorageScope; prefix: string };

export type BatchRemoveItemByPrefixOutput = { scope: StorageScope; items: { [key: string]: JsonValue } };

/**
 * @category Operation
 */
export type BatchRemoveItemInput = { scope: StorageScope; keys: Array<string> };

/**
 * @category Operation
 */
export type BatchRemoveItemOutput = { scope: StorageScope; items: { [key: string]: JsonValue | null } };

/**
 * @category Operation
 */
export type GetItemInput = { key: string; scope: StorageScope };

/**
 * @category Operation
 */
export type GetItemOutput = { key: string; value: OptionalValue; scope: StorageScope };

/**
 * @category Operation
 */
export type PutItemInput = { key: string; scope: StorageScope; value: JsonValue };

/**
 * @category Operation
 */
export type PutItemOutput = Record<string, never>;

/**
 * @category Operation
 */
export type RemoveItemInput = { key: string; scope: StorageScope };

/**
 * @category Operation
 */
export type RemoveItemOutput = { scope: StorageScope; value: JsonValue };
