// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import { JsonValue } from "@repo/moss-bindingutils";
import type { StorageScope } from "./primitives";

/**
 * @category Operation
 */
export type GetItemInput = { key: string; scope: StorageScope };

/**
 * @category Operation
 */
export type GetItemOutput = { key: string; value: JsonValue; scope: StorageScope };

/**
 * @category Operation
 */
export type PutItemInput = { key: string; scope: StorageScope; value: JsonValue };

/**
 * @category Operation
 */
export type PutItemOutput = Record<string, never>;

/**
 * @category Operation
 */
export type RemoveItemInput = { key: string; scope: StorageScope };

/**
 * @category Operation
 */
export type RemoveItemOutput = { success: boolean };
