// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import { JsonValue } from "@repo/moss-bindingutils";
import type { Scope } from "./primitives";

/**
 * @category Operation
 */
export type GetItemInput = { key: string; scope: Scope };

/**
 * @category Operation
 */
export type GetItemOutput = { key: string; value: JsonValue; scope: Scope };
