// @ts-nocheck - File uses recursive schemas that may cause "Type instantiation is excessively deep" errors
// Generated by ts-to-zod
import { z } from "zod";

import { jsonRecordValueSchema, jsonValueSchema } from "@repo/moss-bindingutils";

import { storageScopeSchema } from "./primitives.zod";

export const batchPutItemOutputSchema = z.record(z.string(), z.never());

export const putItemOutputSchema = z.record(z.string(), z.never());
export const batchGetItemInputSchema = z.object({
  scope: storageScopeSchema,
  keys: z.array(z.string()),
});

export const batchGetItemOutputSchema = z.object({
  scope: storageScopeSchema,
  items: z.record(z.string(), jsonRecordValueSchema.nullable()),
});

export const batchPutItemInputSchema = z.object({
  scope: storageScopeSchema,
  items: z.record(z.string(), jsonRecordValueSchema),
});

export const batchRemoveItemInputSchema = z.object({
  scope: storageScopeSchema,
  keys: z.array(z.string()),
});

export const batchRemoveItemOutputSchema = z.object({
  scope: storageScopeSchema,
  items: z.record(z.string(), jsonRecordValueSchema.nullable()),
});

export const getItemInputSchema = z.object({
  key: z.string(),
  scope: storageScopeSchema,
});

export const getItemOutputSchema = z.object({
  key: z.string(),
  value: jsonValueSchema,
  scope: storageScopeSchema,
});

export const putItemInputSchema = z.object({
  key: z.string(),
  scope: storageScopeSchema,
  value: jsonValueSchema,
});

export const removeItemInputSchema = z.object({
  key: z.string(),
  scope: storageScopeSchema,
});

export const removeItemOutputSchema = z.object({
  scope: storageScopeSchema,
  value: jsonValueSchema,
});
