// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

import { JsonValue } from "@repo/moss-bindingutils";

/**
 * @category Primitive
 */
export type OptionalValue = "none" | { "value": JsonValue };

/**
 * @category Primitive
 */
export type StorageScope = "application" | { "workspace": string };
