// @ts-nocheck - File uses recursive schemas that may cause "Type instantiation is excessively deep" errors
// Generated by ts-to-zod
import { jsonValueSchema } from "@repo/moss-bindingutils";
import { z } from "zod";

export const storageScopeSchema = z.union([
  z.literal("application"),
  z.object({
    "workspace": z.string(),
  }),
]);
export const optionalJsonValueSchema = z.union([
  z.literal("none"),
  z.object({
    "value": jsonValueSchema,
  }),
]);
