// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * @category Primitive
 */
export type ChangeBool = { "UPDATE": boolean } | "REMOVE";

/**
 * @category Primitive
 */
export type ChangeJsonValue = { "UPDATE": JsonValue } | "REMOVE";

/**
 * @category Primitive
 */
export type ChangePath = { "UPDATE": string } | "REMOVE";

/**
 * @category Primitive
 */
export type ChangeString = { "UPDATE": string } | "REMOVE";

/**
 * @category Primitive
 */
export type ChangeUsize = { "UPDATE": number } | "REMOVE";

export type JsonValue = number | string | boolean | Array<JsonValue> | { [key in string]?: JsonValue } | null;
