// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ChangeBool = { "UPDATE": boolean } | "REMOVE";

export type ChangeString = { "UPDATE": string } | "REMOVE";

export type ChangeUsize = { "UPDATE": number } | "REMOVE";
