// Generated by ts-to-zod
import { z } from "zod";

export const changeBoolSchema = z.union([
  z.object({
    "UPDATE": z.boolean(),
  }),
  z.literal("REMOVE"),
]);

export const changeStringSchema = z.union([
  z.object({
    "UPDATE": z.string(),
  }),
  z.literal("REMOVE"),
]);

export const changeUsizeSchema = z.union([
  z.object({
    "UPDATE": z.number(),
  }),
  z.literal("REMOVE"),
]);
