[package]
name = "moss_types"
version = "0.1.0"
edition = "2021"

[dependencies]
moss_common.workspace = true

serde_json.workspace = true
serde = { workspace = true, features = ["derive"] }
ts-rs = { workspace = true, features = ["serde-json-impl"] }
