// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * @category Type
 */
export type WorkspaceInfo = { id: string; name: string; lastOpenedAt?: bigint };
