repos:
  - repo: local
    hooks:
      - id: prettier-tailwind
        name: Run Prettier with Tailwind plugin
        entry: npx prettier --plugin=prettier-plugin-tailwindcss --write
        language: system
        files: "\\.(ts|tsx|md)$"
        pass_filenames: true
        stages: [commit]
