// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ResourceClass, ResourceKind, ResourceProtocol } from "./primitives";

export type ResourceSummary = {
  id: string;
  name: string;
  path: string;
  class: ResourceClass;
  kind: ResourceKind;
  protocol?: ResourceProtocol;
};
