// Generated by ts-to-zod
import { z } from "zod";
import { resourceClassSchema, resourceKindSchema, resourceProtocolSchema } from "./primitives.zod";
export const resourceSummarySchema = z.object({
  id: z.string(),
  name: z.string(),
  path: z.string(),
  class: resourceClassSchema,
  kind: resourceKindSchema,
  protocol: resourceProtocolSchema.nullable(),
});
