[package]
name = "moss_workbench"
version = "0.1.0"
edition = "2024"

[dependencies]
moss_applib.workspace = true
moss_workspace.workspace = true
moss_common.workspace = true
moss_fs.workspace = true
moss_storage.workspace = true
moss_activity_indicator.workspace = true
moss_db.workspace = true
moss_text.workspace = true

tokio.workspace = true
anyhow.workspace = true
tauri.workspace = true
serde = { workspace = true, features = ["derive"] }
ts-rs = { workspace = true, features = ["uuid-impl"] }
validator.workspace = true
chrono.workspace = true
uuid = { workspace = true, features = ["serde"] }
derive_more = { workspace = true, features = ["deref", "deref_mut"] }

[dev-dependencies]
moss_applib = { workspace = true, features = ["test"] }
tauri = { workspace = true, features = ["test"] }
moss_testutils.workspace = true
