// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AccountKind, MethodKind } from "./primitives";

/**
 * @category Type
 */
export type AccountInfo = {
  id: string;
  username: string;
  host: string;
  kind: AccountKind;
  method: MethodKind;
  metadata: AccountInfoMetadata;
};

export type AccountInfoMetadata = { expiresAt?: string };

/**
 * @category Type
 */
export type ProfileInfo = { id: string; name: string; accounts: Array<AccountInfo> };
