// Generated by ts-to-zod
import { z } from "zod";
import { accountKindSchema, sessionKindSchema } from "./primitives.zod";
export const accountInfoSchema = z.object({
  id: z.string(),
  username: z.string(),
  host: z.string(),
  kind: accountKindSchema,
  sessionKind: sessionKindSchema,
});

export const profileInfoSchema = z.object({
  id: z.string(),
  name: z.string(),
  accounts: z.array(accountInfoSchema),
});
