// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AccountKind } from "./primitives";

/**
 * @category Type
 */
export type AccountInfo = { id: string; username: string; host: string; kind: AccountKind };

/**
 * @category Type
 */
export type ProfileInfo = { id: string; name: string; accounts: Array<AccountInfo> };
