// Generated by ts-to-zod
import { z } from "zod";
import { accountKindSchema, methodKindSchema } from "./primitives.zod";

export const accountInfoMetadataSchema = z.object({
  expiresAt: z.string().optional(),
});
export const accountInfoSchema = z.object({
  id: z.string(),
  username: z.string(),
  host: z.string(),
  kind: accountKindSchema,
  method: methodKindSchema,
  metadata: accountInfoMetadataSchema,
});

export const profileInfoSchema = z.object({
  id: z.string(),
  name: z.string(),
  accounts: z.array(accountInfoSchema),
});
