// Generated by ts-to-zod
import { z } from "zod";
import { accountAuthMethodKindSchema, accountKindSchema } from "./primitives.zod";

export const accountMetadataSchema = z.object({
  patExpiresAt: z.string().optional(),
});
export const accountInfoSchema = z.object({
  id: z.string(),
  username: z.string(),
  host: z.string(),
  kind: accountKindSchema,
  method: accountAuthMethodKindSchema,
  metadata: accountMetadataSchema,
});

export const profileInfoSchema = z.object({
  id: z.string(),
  name: z.string(),
  accounts: z.array(accountInfoSchema),
});
