// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "../serde_json/JsonValue";

export type HttpMethod = "post" | "get" | "put" | "delete";

export type QueryParamItem = { key: string, value: JsonValue, order?: number, desc?: string, disabled: boolean, options: QueryParamOptions, };

export type QueryParamOptions = { propagate: boolean, };
