// Generated by ts-to-zod
import { localizedStringSchema, notificationLocationSchema } from "@repo/base";
import { z } from "zod";
export const activityEventSchema = z.union([
  z.object({
    "oneshot": z.object({
      id: z.number(),
      activityId: z.string(),
      title: localizedStringSchema,
      detail: localizedStringSchema.optional(),
      location: notificationLocationSchema,
    }),
  }),
  z.object({
    "start": z.object({
      id: z.number(),
      activityId: z.string(),
      title: localizedStringSchema,
      detail: localizedStringSchema.optional(),
      location: notificationLocationSchema,
    }),
  }),
  z.object({
    "progress": z.object({
      id: z.number(),
      activityId: z.string(),
      detail: localizedStringSchema.optional(),
    }),
  }),
  z.object({
    "finish": z.object({
      id: z.number(),
      activityId: z.string(),
    }),
  }),
]);
