// Generated by ts-to-zod
import { z } from "zod";
import { locationSchema } from "./notification/primitives.zod";
export const activityEventSchema = z.union([
  z.object({
    "oneshot": z.object({
      id: z.number(),
      activityId: z.string(),
      title: z.string(),
      detail: z.string().optional(),
      location: locationSchema,
    }),
  }),
  z.object({
    "start": z.object({
      id: z.number(),
      activityId: z.string(),
      title: z.string(),
      detail: z.string().optional(),
      location: locationSchema,
    }),
  }),
  z.object({
    "progress": z.object({
      id: z.number(),
      activityId: z.string(),
      detail: z.string().optional(),
    }),
  }),
  z.object({
    "finish": z.object({
      id: z.number(),
      activityId: z.string(),
    }),
  }),
]);
