// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LocalizedString } from "./language/types";
import type { Location } from "./notification/primitives";

/**
 * @category Event
 */
export type ActivityEvent =
  | {
      "oneshot": {
        id: number;
        activityId: string;
        title: LocalizedString;
        detail?: LocalizedString;
        location: Location;
      };
    }
  | {
      "start": { id: number; activityId: string; title: LocalizedString; detail?: LocalizedString; location: Location };
    }
  | { "progress": { id: number; activityId: string; detail?: LocalizedString } }
  | { "finish": { id: number; activityId: string } };
