// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

import { LocalizedString, NotificationLocation } from "@repo/base";

/**
 * @category Event
 */
export type ActivityEvent =
  | {
      "oneshot": {
        id: number;
        activityId: string;
        title: LocalizedString;
        detail?: LocalizedString;
        location: NotificationLocation;
      };
    }
  | {
      "start": {
        id: number;
        activityId: string;
        title: LocalizedString;
        detail?: LocalizedString;
        location: NotificationLocation;
      };
    }
  | { "progress": { id: number; activityId: string; detail?: LocalizedString } }
  | { "finish": { id: number; activityId: string } };
