// Generated by ts-to-zod
import { localizedStringSchema, notificationLocationSchema } from "@repo/base";
import { z } from "zod";
import { branchInfoSchema } from "./types.zod";

export const streamEnvironmentsEventSchema = z.object({
  id: z.string(),
  projectId: z.string().optional(),
  isActive: z.boolean(),
  name: z.string(),
  order: z.number().optional(),
  totalVariables: z.number(),
});
export const activityEventSchema = z.union([
  z.object({
    "oneshot": z.object({
      id: z.number(),
      activityId: z.string(),
      title: localizedStringSchema,
      detail: localizedStringSchema.optional(),
      location: notificationLocationSchema,
    }),
  }),
  z.object({
    "start": z.object({
      id: z.number(),
      activityId: z.string(),
      title: localizedStringSchema,
      detail: localizedStringSchema.optional(),
      location: notificationLocationSchema,
    }),
  }),
  z.object({
    "progress": z.object({
      id: z.number(),
      activityId: z.string(),
      detail: localizedStringSchema.optional(),
    }),
  }),
  z.object({
    "finish": z.object({
      id: z.number(),
      activityId: z.string(),
    }),
  }),
]);

export const streamProjectsEventSchema = z.object({
  id: z.string(),
  name: z.string(),
  order: z.number().optional(),
  expanded: z.boolean(),
  branch: branchInfoSchema.optional(),
  iconPath: z.string().optional(),
  archived: z.boolean(),
});
