// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import { LocalizedString, NotificationLocation } from "@repo/base";
import type { BranchInfo } from "./types";

/**
 * @category Event
 */
export type ActivityEvent =
  | {
      "oneshot": {
        id: number;
        activityId: string;
        title: LocalizedString;
        detail?: LocalizedString;
        location: NotificationLocation;
      };
    }
  | {
      "start": {
        id: number;
        activityId: string;
        title: LocalizedString;
        detail?: LocalizedString;
        location: NotificationLocation;
      };
    }
  | { "progress": { id: number; activityId: string; detail?: LocalizedString } }
  | { "finish": { id: number; activityId: string } };

/**
 * @category Event
 */
export type StreamEnvironmentsEvent = {
  id: string;
  /**
   * The id of the project that the environment belongs to.
   * If the environment is global, this will be `None`.
   */
  projectId?: string;
  isActive: boolean;
  name: string;
  order?: number;
  totalVariables: number;
};

/**
 * @category Event
 */
export type StreamProjectsEvent = {
  id: string;
  name: string;
  order?: number;
  expanded: boolean;
  branch?: BranchInfo;
  iconPath?: string;
  archived: boolean;
};
