// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import {
  AccountInfo,
  AccountKind,
  ColorThemeInfo,
  ConfigurationSchema,
  ExtensionInfo,
  LanguageInfo,
  ThemeId,
  VariableInfo,
} from "@repo/base";
import { ChangePath, ChangeString, JsonValue } from "@repo/moss-bindingutils";
import type {
  AddVariableParams,
  Contributor,
  CreateProjectGitParams,
  EnvironmentGroup,
  ImportProjectSource,
  UpdateEnvironmentGroupParams,
  UpdateEnvironmentParams,
  UpdateProjectParams,
  UpdateVariableParams,
  VcsInfo,
  WorkspaceInfo,
} from "./types";

export type ActivateEnvironmentInput = { projectId?: string; environmentId: string };

export type ActivateEnvironmentOutput = { environmentId: string };

/**
 * @category Operation
 */
export type AddUserAccountInput = {
  host: string;
  kind: AccountKind;
  /**
   * If a PAT is not provided, we will use OAuth
   */
  pat?: string;
};

/**
 * @category Operation
 */
export type ArchiveProjectInput = { id: string };

/**
 * @category Operation
 */
export type ArchiveProjectOutput = { id: string };

/**
 * @category Operation
 */
export type BatchUpdateEnvironmentGroupInput = { items: Array<UpdateEnvironmentGroupParams> };

/**
 * @category Operation
 */
export type BatchUpdateEnvironmentInput = { items: Array<UpdateEnvironmentParams> };

/**
 * @category Operation
 */
export type BatchUpdateEnvironmentOutput = { ids: Array<string> };

/**
 * @category Operation
 */
export type BatchUpdateProjectInput = { items: Array<UpdateProjectParams> };

/**
 * @category Operation
 */
export type BatchUpdateProjectOutput = { ids: Array<string> };

/**
 * @category Operation
 */
export type CancelRequestInput = { request_id: string };

/**
 * @category Operation
 */
export type CreateEnvironmentInput = {
  projectId?: string;
  name: string;
  order: number;
  color?: string;
  variables: Array<AddVariableParams>;
};

/**
 * @category Operation
 */
export type CreateEnvironmentOutput = { id: string; projectId?: string; name: string; order?: number; color?: string };

/**
 * @category Operation
 */
export type CreateProjectInput = {
  name: string;
  order: number;
  externalPath?: string;
  gitParams?: CreateProjectGitParams;
  iconPath?: string;
};

/**
 * @category Operation
 */
export type CreateProjectOutput = { id: string; name: string; order?: number; expanded: boolean; iconPath?: string };

/**
 * @category Operation
 */
export type DeleteEnvironmentInput = { projectId?: string; id: string };

/**
 * @category Operation
 */
export type DeleteEnvironmentOutput = { id: string };

/**
 * @category Operation
 */
export type DeleteProjectInput = { id: string };

/**
 * @category Operation
 */
export type DeleteProjectOutput = { id: string };

/**
 * @category Operation
 */
export type DeleteWorkspaceInput = { id: string };

/**
 * @category Operation
 */
export type DeleteWorkspaceOutput = { id: string };

/**
 * @category Operation
 */
export type DescribeEnvironmentInput = { id: string };

/**
 * @category Operation
 */
export type DescribeEnvironmentOutput = { variables: VariableInfo };

/**
 * @category Operation
 */
export type DescribeProjectInput = { id: string };

/**
 * @category Operation
 */
export type DescribeProjectOutput = {
  name: string;
  vcs?: VcsInfo;
  contributors: Array<Contributor>;
  createdAt: string;
};

/**
 * @category Operation
 */
export type DownloadExtensionInput = { extensionId: string; version: string };

/**
 * @category Operation
 */
export type ExportProjectInput = {
  id: string;
  /**
   * Path to the folder containing the output archive file
   */
  destination: string;
};

/**
 * @category Operation
 */
export type ExportProjectOutput = { archivePath: string };

/**
 * @category Operation
 */
export type GetColorThemeInput = { id: ThemeId };

/**
 * @category Operation
 */
export type GetColorThemeOutput = { cssContent: string };

/**
 * @category Operation
 */
export type GetTranslationNamespaceInput = { language: string; namespace: string };

/**
 * @category Operation
 */
export type GetTranslationNamespaceOutput = { contents: JsonValue };

/**
 * @category Operation
 */
export type ImportProjectInput = { name: string; order: number; source: ImportProjectSource; iconPath?: string };

/**
 * @category Operation
 */
export type ImportProjectOutput = { id: string; name: string; order?: number; expanded: boolean; iconPath?: string };

/**
 * @category Operation
 */
export type ListColorThemesOutput = Array<ColorThemeInfo>;

export type ListConfigurationSchemasOutput = { schemas: ConfigurationSchema[] };

/**
 * @category Operation
 */
export type ListExtensionsOutput = ExtensionInfo[];

/**
 * @category Operation
 */
export type ListLanguagesOutput = LanguageInfo[];

/**
 * @category Operation
 */
export type ListUserAccountsOutput = { accounts: AccountInfo[] };

/**
 * @category Operation
 */
export type ListWorkspacesOutput = Array<WorkspaceInfo>;

/**
 * @category Operation
 */
export type RemoveUserAccountInput = { id: string };

/**
 * @category Operation
 */
export type StreamEnvironmentsOutput = { groups: Array<EnvironmentGroup> };

/**
 * @category Operation
 */
export type StreamProjectEnvironmentsInput = { projectId: string };

export type StreamProjectEnvironmentsOutput = {};

/**
 * @category Operation
 */
export type StreamProjectsOutput = {};

/**
 * @category Operation
 */
export type UnarchiveProjectInput = { id: string };

/**
 * @category Operation
 */
export type UnarchiveProjectOutput = { id: string };

/**
 * @category Operation
 */
export type UpdateEnvironmentGroupInput = { projectId: string; expanded?: boolean; order?: number };

/**
 * @category Operation
 */
export type UpdateEnvironmentInput = {
  projectId?: string;
  id: string;
  name?: string;
  order?: number;
  color?: ChangeString;
  expanded?: boolean;
  varsToAdd: Array<AddVariableParams>;
  varsToUpdate: Array<UpdateVariableParams>;
  varsToDelete: Array<string>;
};

/**
 * @category Operation
 */
export type UpdateEnvironmentOutput = { id: string };

/**
 * @category Operation
 */
export type UpdateProjectInput = {
  id: string;
  name?: string;
  iconPath?: ChangePath;
  order?: number;
  expanded?: boolean;
};

/**
 * @category Operation
 */
export type UpdateProjectOutput = { id: string };

/**
 * @category Operation
 */
export type UpdateUserAccountInput = { id: string; pat?: string };
