// @ts-nocheck - File uses recursive schemas that may cause "Type instantiation is excessively deep" errors
// Generated by ts-to-zod
import {
  accountInfoSchema,
  accountKindSchema,
  colorThemeInfoSchema,
  configurationSchemaSchema,
  extensionInfoSchema,
  languageInfoSchema,
  themeIdSchema,
} from "@repo/base";
import { changePathSchema, changeStringSchema, jsonValueSchema } from "@repo/moss-bindingutils";
import { z } from "zod";
import {
  contributorSchema,
  createProjectGitParamsSchema,
  importProjectSourceSchema,
  updateProjectParamsSchema,
  vcsInfoSchema,
  workspaceInfoSchema,
} from "./types.zod";

export const archiveProjectInputSchema = z.object({
  id: z.string(),
});

export const archiveProjectOutputSchema = z.object({
  id: z.string(),
});

export const batchUpdateProjectOutputSchema = z.object({
  ids: z.array(z.string()),
});

export const cancelRequestInputSchema = z.object({
  request_id: z.string(),
});

export const createProjectOutputSchema = z.object({
  id: z.string(),
  name: z.string(),
  order: z.number().optional(),
  expanded: z.boolean(),
  iconPath: z.string().optional(),
});

export const deleteProjectInputSchema = z.object({
  id: z.string(),
});

export const deleteProjectOutputSchema = z.object({
  id: z.string(),
});

export const deleteWorkspaceInputSchema = z.object({
  id: z.string(),
});

export const deleteWorkspaceOutputSchema = z.object({
  id: z.string(),
});

export const describeProjectInputSchema = z.object({
  id: z.string(),
});

export const downloadExtensionInputSchema = z.object({
  extensionId: z.string(),
  version: z.string(),
});

export const exportProjectInputSchema = z.object({
  id: z.string(),
  destination: z.string(),
});

export const exportProjectOutputSchema = z.object({
  archivePath: z.string(),
});

export const getColorThemeOutputSchema = z.object({
  cssContent: z.string(),
});

export const getTranslationNamespaceInputSchema = z.object({
  language: z.string(),
  namespace: z.string(),
});

export const importProjectOutputSchema = z.object({
  id: z.string(),
  name: z.string(),
  order: z.number().optional(),
  expanded: z.boolean(),
  iconPath: z.string().optional(),
});

export const removeUserAccountInputSchema = z.object({
  id: z.string(),
});

export const streamProjectsOutputSchema = z.object({});

export const unarchiveProjectInputSchema = z.object({
  id: z.string(),
});

export const unarchiveProjectOutputSchema = z.object({
  id: z.string(),
});

export const updateProjectOutputSchema = z.object({
  id: z.string(),
});

export const updateUserAccountInputSchema = z.object({
  id: z.string(),
  pat: z.string().optional(),
});
export const addUserAccountInputSchema = z.object({
  host: z.string(),
  kind: accountKindSchema,
  pat: z.string().optional(),
});

export const batchUpdateProjectInputSchema = z.object({
  items: z.array(updateProjectParamsSchema),
});

export const createProjectInputSchema = z.object({
  name: z.string(),
  order: z.number(),
  externalPath: z.string().optional(),
  gitParams: createProjectGitParamsSchema.optional(),
  iconPath: z.string().optional(),
});

export const describeProjectOutputSchema = z.object({
  name: z.string(),
  vcs: vcsInfoSchema.optional(),
  contributors: z.array(contributorSchema),
  createdAt: z.string(),
});

export const getColorThemeInputSchema = z.object({
  id: themeIdSchema,
});

export const getTranslationNamespaceOutputSchema = z.object({
  contents: jsonValueSchema,
});

export const importProjectInputSchema = z.object({
  name: z.string(),
  order: z.number(),
  source: importProjectSourceSchema,
  iconPath: z.string().optional(),
});

export const listColorThemesOutputSchema = z.array(colorThemeInfoSchema);

export const listConfigurationSchemasOutputSchema = z.object({
  schemas: z.array(configurationSchemaSchema),
});

export const listExtensionsOutputSchema = z.array(extensionInfoSchema);

export const listLanguagesOutputSchema = z.array(languageInfoSchema);

export const listUserAccountsOutputSchema = z.object({
  accounts: z.array(accountInfoSchema),
});

export const listWorkspacesOutputSchema = z.array(workspaceInfoSchema);

export const updateProjectInputSchema = z.object({
  id: z.string(),
  name: z.string().optional(),
  repository: changeStringSchema.optional(),
  iconPath: changePathSchema.optional(),
  order: z.number().optional(),
  expanded: z.boolean().optional(),
});
