// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import {
  AccountInfo,
  AccountKind,
  ColorThemeInfo,
  ConfigurationSchema,
  ExtensionInfo,
  LanguageInfo,
  ThemeId,
} from "@repo/base";
import { ChangePath, ChangeString, JsonValue } from "@repo/moss-bindingutils";
import type {
  Contributor,
  CreateProjectGitParams,
  ImportProjectSource,
  UpdateProjectParams,
  VcsInfo,
  WorkspaceInfo,
} from "./types";

/**
 * @category Operation
 */
export type AddUserAccountInput = {
  host: string;
  kind: AccountKind;
  /**
   * If a PAT is not provided, we will use OAuth
   */
  pat?: string;
};

/**
 * @category Operation
 */
export type ArchiveProjectInput = { id: string };

/**
 * @category Operation
 */
export type ArchiveProjectOutput = { id: string };

/**
 * @category Operation
 */
export type BatchUpdateProjectInput = { items: Array<UpdateProjectParams> };

/**
 * @category Operation
 */
export type BatchUpdateProjectOutput = { ids: Array<string> };

/**
 * @category Operation
 */
export type CancelRequestInput = { request_id: string };

/**
 * @category Operation
 */
export type CreateProjectInput = {
  name: string;
  order: number;
  externalPath?: string;
  gitParams?: CreateProjectGitParams;
  iconPath?: string;
};

/**
 * @category Operation
 */
export type CreateProjectOutput = { id: string; name: string; order?: number; expanded: boolean; iconPath?: string };

/**
 * @category Operation
 */
export type DeleteProjectInput = { id: string };

/**
 * @category Operation
 */
export type DeleteProjectOutput = { id: string };

/**
 * @category Operation
 */
export type DeleteWorkspaceInput = { id: string };

/**
 * @category Operation
 */
export type DeleteWorkspaceOutput = { id: string };

/**
 * @category Operation
 */
export type DescribeProjectInput = { id: string };

/**
 * @category Operation
 */
export type DescribeProjectOutput = {
  name: string;
  vcs?: VcsInfo;
  contributors: Array<Contributor>;
  createdAt: string;
};

/**
 * @category Operation
 */
export type DownloadExtensionInput = { extensionId: string; version: string };

/**
 * @category Operation
 */
export type ExportProjectInput = {
  id: string;
  /**
   * Path to the folder containing the output archive file
   */
  destination: string;
};

/**
 * @category Operation
 */
export type ExportProjectOutput = { archivePath: string };

/**
 * @category Operation
 */
export type GetColorThemeInput = { id: ThemeId };

/**
 * @category Operation
 */
export type GetColorThemeOutput = { cssContent: string };

/**
 * @category Operation
 */
export type GetTranslationNamespaceInput = { language: string; namespace: string };

/**
 * @category Operation
 */
export type GetTranslationNamespaceOutput = { contents: JsonValue };

/**
 * @category Operation
 */
export type ImportProjectInput = { name: string; order: number; source: ImportProjectSource; iconPath?: string };

/**
 * @category Operation
 */
export type ImportProjectOutput = { id: string; name: string; order?: number; expanded: boolean; iconPath?: string };

/**
 * @category Operation
 */
export type ListColorThemesOutput = Array<ColorThemeInfo>;

export type ListConfigurationSchemasOutput = { schemas: ConfigurationSchema[] };

/**
 * @category Operation
 */
export type ListExtensionsOutput = ExtensionInfo[];

/**
 * @category Operation
 */
export type ListLanguagesOutput = LanguageInfo[];

/**
 * @category Operation
 */
export type ListUserAccountsOutput = { accounts: AccountInfo[] };

/**
 * @category Operation
 */
export type ListWorkspacesOutput = Array<WorkspaceInfo>;

/**
 * @category Operation
 */
export type RemoveUserAccountInput = { id: string };

/**
 * @category Operation
 */
export type StreamProjectsOutput = {};

/**
 * @category Operation
 */
export type UnarchiveProjectInput = { id: string };

/**
 * @category Operation
 */
export type UnarchiveProjectOutput = { id: string };

/**
 * @category Operation
 */
export type UpdateProjectInput = {
  id: string;
  name?: string;
  repository?: ChangeString;
  iconPath?: ChangePath;
  order?: number;
  expanded?: boolean;
};

/**
 * @category Operation
 */
export type UpdateProjectOutput = { id: string };

/**
 * @category Operation
 */
export type UpdateUserAccountInput = { id: string; pat?: string };
