// @ts-nocheck - File uses recursive schemas that may cause "Type instantiation is excessively deep" errors
// Generated by ts-to-zod
import {
  accountInfoSchema,
  accountKindSchema,
  colorThemeInfoSchema,
  configurationSchemaSchema,
  extensionInfoSchema,
  languageInfoSchema,
  themeIdSchema,
} from "@repo/base";
import { jsonValueSchema } from "@repo/moss-bindingutils";
import { z } from "zod";
import { workspaceInfoSchema } from "./types.zod";

export const cancelRequestInputSchema = z.object({
  request_id: z.string(),
});

export const deleteWorkspaceInputSchema = z.object({
  id: z.string(),
});

export const deleteWorkspaceOutputSchema = z.object({
  id: z.string(),
});

export const downloadExtensionInputSchema = z.object({
  extension_id: z.string(),
  version: z.string(),
});

export const getColorThemeOutputSchema = z.object({
  cssContent: z.string(),
});

export const getTranslationNamespaceInputSchema = z.object({
  language: z.string(),
  namespace: z.string(),
});

export const removeUserAccountInputSchema = z.object({
  id: z.string(),
});

export const updateUserAccountInputSchema = z.object({
  id: z.string(),
  pat: z.string().optional(),
});
export const addUserAccountInputSchema = z.object({
  host: z.string(),
  kind: accountKindSchema,
  pat: z.string().optional(),
});

export const getColorThemeInputSchema = z.object({
  id: themeIdSchema,
});

export const getTranslationNamespaceOutputSchema = z.object({
  contents: jsonValueSchema,
});

export const listColorThemesOutputSchema = z.array(colorThemeInfoSchema);

export const listConfigurationSchemasOutputSchema = z.object({
  schemas: z.array(configurationSchemaSchema),
});

export const listExtensionsOutputSchema = z.array(extensionInfoSchema);

export const listLanguagesOutputSchema = z.array(languageInfoSchema);

export const listUserAccountsOutputSchema = z.object({
  accounts: z.array(accountInfoSchema),
});

export const listWorkspacesOutputSchema = z.array(workspaceInfoSchema);
