// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import { ColorThemeInfo, ConfigurationSchema, ExtensionInfo, ThemeId } from "@repo/base";
import type { WorkspaceInfo } from "./types";

/**
 * @category Operation
 */
export type CancelRequestInput = { request_id: string };

/**
 * @category Operation
 */
export type DeleteWorkspaceInput = { id: string };

/**
 * @category Operation
 */
export type DeleteWorkspaceOutput = { id: string };

/**
 * @category Operation
 */
export type GetColorThemeInput = { id: ThemeId };

/**
 * @category Operation
 */
export type GetColorThemeOutput = { cssContent: string };

/**
 * @category Operation
 */
export type ListColorThemesOutput = Array<ColorThemeInfo>;

export type ListConfigurationSchemasOutput = { schemas: ConfigurationSchema[] };

/**
 * @category Operation
 */
export type ListExtensionsOutput = ExtensionInfo[];

/**
 * @category Operation
 */
export type ListWorkspacesOutput = Array<WorkspaceInfo>;

/**
 * @category Operation
 *
 * Used for updating any workspace from any window.
 */
export type UpdateWorkspaceInput = {
  id: string;
  /**
   * A new name for the workspace, if provided, the workspace
   * will be renamed to this name.
   */
  name?: string;
};

/**
 * @category Operation
 */
export type UpdateWorkspaceOutput = Record<string, never>;
