// Generated by ts-to-zod
import { colorThemeInfoSchema, configurationSchemaSchema, extensionInfoSchema, themeIdSchema } from "@repo/base";
import { z } from "zod";
import { workspaceInfoSchema } from "./types.zod";

export const cancelRequestInputSchema = z.object({
  request_id: z.string(),
});

export const deleteWorkspaceInputSchema = z.object({
  id: z.string(),
});

export const deleteWorkspaceOutputSchema = z.object({
  id: z.string(),
});

export const getColorThemeOutputSchema = z.object({
  cssContent: z.string(),
});

export const updateWorkspaceInputSchema = z.object({
  id: z.string(),
  name: z.string().optional(),
});

export const updateWorkspaceOutputSchema = z.record(z.string(), z.never());
export const getColorThemeInputSchema = z.object({
  id: themeIdSchema,
});

export const listColorThemesOutputSchema = z.array(colorThemeInfoSchema);

export const listConfigurationSchemasOutputSchema = z.object({
  schemas: z.array(configurationSchemaSchema),
});

export const listExtensionsOutputSchema = z.array(extensionInfoSchema);

export const listWorkspacesOutputSchema = z.array(workspaceInfoSchema);
