// Generated by ts-to-zod
import { changePathSchema, changeStringSchema } from "@repo/moss-bindingutils";
import { z } from "zod";

export const branchInfoSchema = z.object({
  name: z.string(),
  ahead: z.number().optional(),
  behind: z.number().optional(),
});

export const contributorSchema = z.object({
  name: z.string(),
  avatarUrl: z.string().optional(),
});

export const gitHubCreateParamsSchema = z.object({
  accountId: z.string(),
  repository: z.string(),
  branch: z.string(),
});

export const gitLabCreateParamsSchema = z.object({
  accountId: z.string(),
  repository: z.string(),
  branch: z.string(),
});

export const createProjectGitParamsSchema = z.union([
  z.object({
    "gitHub": gitHubCreateParamsSchema,
  }),
  z.object({
    "gitLab": gitLabCreateParamsSchema,
  }),
]);

export const exportProjectParamsSchema = z.object({
  id: z.string(),
  destination: z.string(),
});

export const gitHubVcsInfoSchema = z.object({
  branch: branchInfoSchema,
  url: z.string(),
  updatedAt: z.string().optional(),
  owner: z.string().optional(),
});

export const gitLabVcsInfoSchema = z.object({
  branch: branchInfoSchema,
  url: z.string(),
  updatedAt: z.string().optional(),
  owner: z.string().optional(),
});

export const importArchiveParamsSchema = z.object({
  archivePath: z.string(),
});

export const importDiskParamsSchema = z.object({
  externalPath: z.string(),
});

export const importGitHubParamsSchema = z.object({
  accountId: z.string(),
  repository: z.string(),
  branch: z.string().optional(),
});

export const importGitLabParamsSchema = z.object({
  accountId: z.string(),
  repository: z.string(),
  branch: z.string().optional(),
});

export const importProjectSourceSchema = z.union([
  z.object({
    "gitHub": importGitHubParamsSchema,
  }),
  z.object({
    "gitLab": importGitLabParamsSchema,
  }),
  z.object({
    "archive": importArchiveParamsSchema,
  }),
  z.object({
    "disk": importDiskParamsSchema,
  }),
]);

export const optionsSchema = z.object({
  request_id: z.string().optional(),
  timeout: z.bigint().optional(),
});

export const vcsInfoSchema = z.union([
  z.object({
    "gitHub": gitHubVcsInfoSchema,
  }),
  z.object({
    "gitLab": gitLabVcsInfoSchema,
  }),
]);

export const workspaceInfoSchema = z.object({
  id: z.string(),
  name: z.string(),
  lastOpenedAt: z.bigint().optional(),
});
export const createProjectParamsSchema = z.object({
  name: z.string(),
  order: z.number(),
  externalPath: z.string().optional(),
  gitParams: createProjectGitParamsSchema.optional(),
  iconPath: z.string().optional(),
});

export const importProjectParamsSchema = z.object({
  name: z.string(),
  order: z.number(),
  source: importProjectSourceSchema,
  iconPath: z.string().optional(),
});

export const updateProjectParamsSchema = z.object({
  id: z.string(),
  name: z.string().optional(),
  repository: changeStringSchema.optional(),
  iconPath: changePathSchema.optional(),
  order: z.number().optional(),
  expanded: z.boolean().optional(),
});
