// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Configuration options for API operations.
 *
 * This struct provides configurable parameters that affect the behavior of API operations,
 * particularly timeout handling for asynchronous operations. It is commonly used with
 * the `with_timeout` utility function to wrap async operations with configurable timeouts.
 *
 * @category Type
 */
export type Options = {
  /**
   * Optional request ID for API operations.
   */
  request_id?: string;
  /**
   * Optional timeout duration for API operations in seconds.
   *
   * When `Some(value)`, the operation will timeout after the specified number of seconds.
   * When `None`, the operation will use the default timeout of 30 seconds
   * (defined by `DEFAULT_OPERATION_TIMEOUT`).
   *
   * # Frontend Note
   *
   * The timeout value is converted to a `Duration` internally using `Duration::from_secs()`,
   * so the minimum granularity is 1 second.
   */
  timeout?: bigint;
};

/**
 * @category Type
 */
export type WorkspaceInfo = { id: string; name: string; lastOpenedAt?: bigint };
