// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

import { ChangePath, ChangeString } from "@repo/moss-bindingutils";

/**
 * @category Type
 */
export type BranchInfo = { name: string; ahead?: number; behind?: number };

/**
 * @category Type
 */
export type Contributor = { name: string; avatarUrl?: string };

export type CreateProjectGitParams = { "gitHub": GitHubCreateParams } | { "gitLab": GitLabCreateParams };

export type CreateProjectParams = {
  name: string;
  order: number;
  externalPath?: string;
  gitParams?: CreateProjectGitParams;
  iconPath?: string;
};

export type ExportProjectParams = {
  id: string;
  /**
   * Path to the folder containing the output archive file
   */
  destination: string;
};

export type GitHubCreateParams = {
  accountId: string;
  repository: string;
  /**
   * The name of the default branch
   */
  branch: string;
};

/**
 * @category Type
 */
export type GitHubVcsInfo = { branch: BranchInfo; url: string; updatedAt?: string; owner?: string };

export type GitLabCreateParams = {
  accountId: string;
  repository: string;
  /**
   * The name of the default branch
   */
  branch: string;
};

/**
 * @category Type
 */
export type GitLabVcsInfo = { branch: BranchInfo; url: string; updatedAt?: string; owner?: string };

/**
 * @category Type
 */
export type ImportArchiveParams = { archivePath: string };

/**
 * @category Type
 */
export type ImportDiskParams = { externalPath: string };

/**
 * @category Type
 */
export type ImportGitHubParams = {
  accountId: string;
  repository: string;
  /**
   * If provided, this branch will be checked out instead of the default branch
   */
  branch?: string;
};

/**
 * @category Type
 */
export type ImportGitLabParams = {
  accountId: string;
  repository: string;
  /**
   * If provided, this branch will be checked out instead of the default branch
   */
  branch?: string;
};

export type ImportProjectParams = { name: string; order: number; source: ImportProjectSource; iconPath?: string };

/**
 * @category Type
 */
export type ImportProjectSource =
  | { "gitHub": ImportGitHubParams }
  | { "gitLab": ImportGitLabParams }
  | { "archive": ImportArchiveParams }
  | { "disk": ImportDiskParams };

/**
 * Configuration options for API operations.
 *
 * This struct provides configurable parameters that affect the behavior of API operations,
 * particularly timeout handling for asynchronous operations. It is commonly used with
 * the `with_timeout` utility function to wrap async operations with configurable timeouts.
 *
 * @category Type
 */
export type Options = {
  /**
   * Optional request ID for API operations.
   */
  request_id?: string;
  /**
   * Optional timeout duration for API operations in seconds.
   *
   * When `Some(value)`, the operation will timeout after the specified number of seconds.
   * When `None`, the operation will use the default timeout of 30 seconds
   * (defined by `DEFAULT_OPERATION_TIMEOUT`).
   *
   * # Frontend Note
   *
   * The timeout value is converted to a `Duration` internally using `Duration::from_secs()`,
   * so the minimum granularity is 1 second.
   */
  timeout?: bigint;
};

/**
 * @category Type
 */
export type UpdateProjectParams = {
  id: string;
  name?: string;
  repository?: ChangeString;
  iconPath?: ChangePath;
  order?: number;
  expanded?: boolean;
};

/**
 * @category Type
 */
export type VcsInfo = { "gitHub": GitHubVcsInfo } | { "gitLab": GitLabVcsInfo };

/**
 * @category Type
 */
export type WorkspaceInfo = { id: string; name: string; lastOpenedAt?: bigint };
