// Generated by ts-to-zod
import { z } from "zod";

export const contributorSchema = z.object({
  name: z.string(),
  avatar_url: z.string(),
});

export const repositoryInfoSchema = z.object({
  createdAt: z.string(),
  updatedAt: z.string(),
  owner: z.string(),
});
