// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * @category Type
 */
export type Contributor = { name: string; avatar_url: string };

/**
 * @category Type
 */
export type RepositoryMetadata = {
  /**
   * A timestamp like 2024-10-05T12:19:15Z
   */
  updatedAt: string;
  owner: string;
};

/**
 * @category Type
 */
export type UserInfo = { name: string; email: string };
