// Generated by ts-to-zod
import { z } from "zod";

export const contributorSchema = z.object({
  name: z.string(),
  avatar_url: z.string(),
});

export const repositoryMetadataSchema = z.object({
  updatedAt: z.string(),
  owner: z.string(),
});

export const userInfoSchema = z.object({
  name: z.string(),
  email: z.string(),
});
