[package]
name = "moss_file"
version = "0.1.0"
edition = "2024"

[dependencies]
moss_fs.workspace = true

toml_edit.workspace = true
toml.workspace = true
tokio.workspace = true
serde.workspace = true
anyhow.workspace = true
