cargo-features = ["edition2024"]

[package]
name = "moss_activity_indicator"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow.workspace = true
serde.workspace = true
tauri.workspace = true
ts-rs.workspace = true


