// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./serde_json/JsonValue";
import type { LocaleInfo } from "./types";

export type GetTranslationsInput = { language: string; namespace: string };

export type GetTranslationsOutput = JsonValue;

export type ListLocalesOutput = { contents: Array<LocaleInfo> };
