// This file was generated by misc/importer.py. Do not edit this file manually.
//
// The necessary import statements have been automatically added by a Python script.
// This ensures that all required dependencies are correctly referenced and available
// within this module.

import type { LocaleInfo } from "./types";
import type { JsonValue } from "@repo/bindings-utils";

//
// If you need to add or modify imports, please update the package.json and
// re-run `make gen-models` it to regenerate the file accordingly.

export type GetTranslationsInput = { language: string; namespace: string };

export type GetTranslationsOutput = JsonValue;

export type ListLocalesOutput = Array<LocaleInfo>;
