// Generated by ts-to-zod
import { jsonValueSchema } from "@repo/bindings-utils";
import { z } from "zod";
import { localeInfoSchema } from "./types.zod";

export const getTranslationsInputSchema = z.object({
  language: z.string(),
  namespace: z.string(),
});
export const getTranslationsOutputSchema = jsonValueSchema;

export const listLocalesOutputSchema = z.array(localeInfoSchema);
