// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LocaleDescriptor } from "./types";

export type GetTranslationsInput = { language: string, namespace: string, };

export type ListLocalesOutput = { contents: Array<LocaleDescriptor>, };
