// Generated by ts-to-zod
import { z } from "zod";

export const localeInfoSchema = z.object({
  identifier: z.string(),
  displayName: z.string(),
  code: z.string(),
  direction: z.string().optional(),
  isDefault: z.boolean().optional(),
});
