// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type LocaleDescriptor = { identifier: string; displayName: string; code: string; direction?: string };
