[package]
name = "moss_contentmodel"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio.workspace = true
jsonptr.workspace = true
json-patch.workspace = true
serde_json.workspace = true
hcl-rs.workspace = true
async-trait.workspace = true
