// This file was generated by lezer-generator. You probably shouldn't edit it.
export const Raw = 1,
  Input = 2,
  Variable = 3,
  VarStart = 4,
  Identifier = 5,
  VarEnd = 6,
  PathParam = 7,
  Slash = 8,
  PathMarker = 9;
