// Generated by ts-to-zod
import { z } from "zod";
import { openInTargetSchema } from "./types.zod";

export const mainWindowCreateWorkspaceOutputSchema = z.object({
  id: z.string(),
  willReplace: z.boolean(),
});

export const mainWindowUpdateWorkspaceInputSchema = z.object({
  name: z.string().optional(),
});

export const mainWindowUpdateWorkspaceOutputSchema = z.record(z.string(), z.never());
export const mainWindowCreateWorkspaceInputSchema = z.object({
  name: z.string(),
  openOnCreation: openInTargetSchema,
});

export const mainWindowOpenWorkspaceInputSchema = z.object({
  id: z.string(),
  openInTarget: openInTargetSchema,
});
