// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ResourceClass, ResourceKind, ResourceProtocol } from "../resource/primitives";

export type ListProjectResourceItem = {
  id: string;
  name: string;
  path: ResourcePath;
  class: ResourceClass;
  kind: ResourceKind;
  protocol: ResourceProtocol | null;
};

export type ListProjectResourcesMode = "LOAD_ROOT" | { "RELOAD_PATH": string };

/**
 * @category Type
 */
export type OpenInTarget = "NEW_WINDOW" | "CURRENT_WINDOW";

/**
 * @category Primitive
 */
export type ResourcePath = { raw: string; segments: Array<string> };
