// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ListProjectResourcesMode = "LOAD_ROOT" | { "RELOAD_PATH": string };

/**
 * @category Type
 */
export type OpenInTarget = "NEW_WINDOW" | "CURRENT_WINDOW";
