// Generated by ts-to-zod
import { resourceClassSchema, resourceKindSchema, resourceProtocolSchema } from "@repo/base";
import { z } from "zod";

export const resourcePathSchema = z.object({
  raw: z.string(),
  segments: z.array(z.string()),
});

export const listProjectResourcesModeSchema = z.union([
  z.literal("LOAD_ROOT"),
  z.object({
    "RELOAD_PATH": z.string(),
  }),
]);

export const openInTargetSchema = z.union([z.literal("NEW_WINDOW"), z.literal("CURRENT_WINDOW")]);
export const listProjectResourceItemSchema = z.object({
  id: z.string(),
  name: z.string(),
  path: resourcePathSchema,
  class: resourceClassSchema,
  kind: resourceKindSchema,
  protocol: resourceProtocolSchema.optional(),
});
