// Generated by ts-to-zod
import { z } from "zod";

export const listProjectResourcesModeSchema = z.union([
  z.literal("LOAD_ROOT"),
  z.object({
    "RELOAD_PATH": z.string(),
  }),
]);

export const openInTargetSchema = z.union([z.literal("NEW_WINDOW"), z.literal("CURRENT_WINDOW")]);
