// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OpenInTarget } from "./types";

/**
 * @category Operation
 */
export type MainWindow_CreateWorkspaceInput = { name: string; openOnCreation?: OpenInTarget };

/**
 * @category Operation
 */
export type MainWindow_CreateWorkspaceOutput = {
  id: string;
  /**
   * Whether the workspace was replaced by the new one.
   * This is only true if the workspace was created in the same window.
   *
   * Technically, this field doesn't carry any functionality and remains for
   * backward compatibility, since now the frontend can determine whether to
   * replace the workspace based on the `open_on_creation` parameter.
   */
  willReplace: boolean;
};

/**
 * @category Operation
 *
 * Used only for the update operation from the main window, specifically to modify the active workspace.
 */
export type MainWindow_UpdateWorkspaceInput = {
  /**
   * A new name for the workspace, if provided, the workspace
   * will be renamed to this name.
   */
  name?: string;
};

/**
 * @category Operation
 */
export type MainWindow_UpdateWorkspaceOutput = Record<string, never>;
