// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ParsedUrl = {
  schemePart?: ParsedValue;
  hostPart: Array<ParsedValue>;
  pathPart: Array<ParsedValue>;
  queryPart: Array<[string, ParsedValue]>;
  fragmentPart?: ParsedValue;
};

export type ParsedValue = { "string": string } | { "variable": string } | { "composite": Array<ParsedValue> };
