// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ParsedUrl = {
  schemePart: Array<ParsedValue>;
  hostPart: Array<ParsedValue>;
  pathPart: Array<ParsedValue>;
  queryPart: Array<QueryParam>;
  fragmentPart?: Array<ParsedValue>;
  raw: Array<ParsedValue>;
};

export type ParsedValue = { "string": string } | { "variable": string } | { "pathVariable": string };

export type QueryParam = { key: Array<ParsedValue>; value?: Array<ParsedValue> };
