// Generated by ts-to-zod
import { z } from "zod";
import { type ParsedValue } from "./types";

export const parsedValueSchema: z.ZodSchema<ParsedValue> = z.lazy(() =>
  z.union([
    z.object({
      "string": z.string(),
    }),
    z.object({
      "variable": z.string(),
    }),
    z.object({
      "composite": z.array(parsedValueSchema),
    }),
  ])
);

export const parsedUrlSchema = z.object({
  schemePart: parsedValueSchema.optional(),
  hostPart: z.array(parsedValueSchema),
  pathPart: z.array(parsedValueSchema),
  queryPart: z.array(z.tuple([z.string(), parsedValueSchema])),
  fragmentPart: parsedValueSchema.optional(),
});
