// @ts-nocheck - File uses recursive schemas that may cause "Type instantiation is excessively deep" errors
// Generated by ts-to-zod
import { jsonValueSchema } from "@repo/moss-bindingutils";
import { z } from "zod";
export const variableInfoSchema = z.object({
  id: z.string(),
  name: z.string(),
  globalValue: jsonValueSchema.optional(),
  localValue: jsonValueSchema.optional(),
  disabled: z.boolean(),
  order: z.number().optional(),
  desc: z.string().optional(),
});

export const environmentInfoSchema = z.object({
  id: z.string(),
  projectId: z.string().optional(),
  name: z.string(),
  displayName: z.string(),
  order: z.number(),
  color: z.string().optional(),
  variables: z.array(variableInfoSchema),
});
