// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

import { JsonValue } from "@repo/moss-bindingutils";

/**
 * @category Type
 */
export type EnvironmentInfo = {
  id: string;
  projectId?: string;
  name: string;
  displayName: string;
  order: number;
  color?: string;
  variables: Array<VariableInfo>;
};

/**
 * @category Type
 */
export type VariableInfo = {
  id: string;
  name: string;
  globalValue?: JsonValue;
  localValue?: JsonValue;
  disabled: boolean;
  order?: number;
  desc?: string;
};
