// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * @category Primitive
 *
 * Represents where progress or transient messages are displayed.
 *
 * Use `Location` to route UI messages to a specific surface within the
 * application shell. Variants are ordered from most global to most
 * ephemeral.
 *
 * - `Window`: Application-wide surface (e.g., status area).
 * - `Notification`: Persistent, actionable message in the notifications UI.
 * - `Toast`: Short-lived, non-blocking overlay near the edge of the window.
 *
 * # Semantics
 * * `Window` is suitable for low-noise, ambient progress (spinners, brief text).
 * * `Notification` is used for items that may require user attention or actions.
 * * `Toast` is for ephemeral hints that disappear automatically.
 */
export type NotificationLocation = "window" | "notification" | "toast";
