// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { QueryParamItem } from "../types/request";

export type CreateCollectionInput = { name: string, path: string, repo?: string, };

export type CreateRequestInput = { name: string, queryParams: Array<QueryParamItem>, };

export type OverviewCollectionOutput = { name: string, path: string, order?: number, };
