// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HeaderParamItem } from "../types/request";
import type { HttpMethod } from "../types/request";
import type { PathParamItem } from "../types/request";
import type { QueryParamItem } from "../types/request";
import type { RequestBody } from "../types/request";
import type { RequestType } from "../collection";

export type CreateRequestInput = {
  name: string;
  relativePath?: string;
  url?: string;
  payload?: CreateRequestProtocolSpecificPayload;
};

export type CreateRequestOutput = { key: bigint };

export type CreateRequestProtocolSpecificPayload = {
  "http": {
    method: HttpMethod;
    query_params: Array<QueryParamItem>;
    path_params: Array<PathParamItem>;
    headers: Array<HeaderParamItem>;
    body: RequestBody | null;
  };
};

export type DeleteRequestInput = { key: bigint };

export type ListRequestsOutput = Array<RequestInfo>;

export type RenameRequestInput = { key: bigint; newName: string };

export type RequestInfo = {
  key: bigint;
  name: string;
  requestDirRelativePath: string;
  order: number | null;
  typ: RequestType;
};
