pub mod batch_delete_log;
pub mod describe_state;
pub mod get_color_theme;
pub mod get_translations;
pub mod list_color_themes;
pub mod list_locales;
pub mod list_logs;
pub mod set_color_theme;
pub mod set_locale;
