pub mod batch_delete_log;
pub mod cancel_request;
pub mod close_workspace;
pub mod create_workspace;
pub mod delete_workspace;
pub mod describe_app_state;
pub mod get_color_theme;
pub mod get_translations;
pub mod list_color_themes;
pub mod list_locales;
pub mod list_logs;
pub mod list_workspaces;
mod log_in_with_github;
mod log_in_with_gitlab;
pub mod open_workspace;
pub mod set_color_theme;
pub mod set_locale;
pub mod update_workspace;
