cargo-features = ["edition2024"]

[package]
name = "moss_state"
version = "0.1.0"
edition = "2024"

[dependencies]
moss_app.workspace = true
moss_text.workspace = true
moss_theme.workspace = true
moss_nls.workspace = true
moss_tauri.workspace = true

anyhow.workspace = true
tauri.workspace = true
thiserror.workspace = true
ts-rs.workspace = true
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
parking_lot.workspace = true
dashmap.workspace = true
