// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Defaults } from "./types";
import type { Preferences } from "./types";

export type DescribeAppStateOutput = { preferences: Preferences, defaults: Defaults, };
