// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import { LocaleInfo } from "@repo/moss-nls";
import { ColorThemeInfo } from "@repo/moss-theme";
import type { Defaults, Preferences } from "./types";

export type DescribeAppStateOutput = { preferences: Preferences; defaults: Defaults; lastWorkspace?: string };

export type SetColorThemeInput = { themeInfo: ColorThemeInfo };

export type SetLocaleInput = { localeInfo: LocaleInfo };
