// This file was generated by misc/importer.py. Do not edit this file manually.
//
// The necessary import statements have been automatically added by a Python script.
// This ensures that all required dependencies are correctly referenced and available
// within this module.

import type { Defaults, Preferences } from "./types";
import type { ColorThemeInfo } from "@repo/moss-theme";
import type { LocaleInfo } from "@repo/moss-nls";

//
// If you need to add or modify imports, please update the package.json and
// re-run `make gen-models` it to regenerate the file accordingly.

export type DescribeAppStateOutput = { preferences: Preferences; defaults: Defaults };

export type SetColorThemeInput = { themeInfo: ColorThemeInfo };

export type SetLocaleInput = { localeInfo: LocaleInfo };
