// Generated by ts-to-zod
import { z } from "zod";
import { defaultsSchema } from "./types.zod";
import { preferencesSchema } from "./types.zod";
import { colorThemeInfoSchema } from "@repo/moss-theme";
import { localeInfoSchema } from "@repo/moss-nls";
export const describeAppStateOutputSchema = z.object({
  preferences: preferencesSchema,
  defaults: defaultsSchema,
  lastWorkspace: z.string().optional(),
});

export const setColorThemeInputSchema = z.object({
  themeInfo: colorThemeInfoSchema,
});

export const setLocaleInputSchema = z.object({
  localeInfo: localeInfoSchema,
});
