// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

import { LocaleInfo } from "@repo/moss-nls";
import { ColorThemeInfo } from "@repo/moss-theme";

export type Defaults = { theme: ColorThemeInfo; locale: LocaleInfo };

export type Preferences = { theme?: ColorThemeInfo; locale?: LocaleInfo };
