// Generated by ts-to-zod
import { z } from "zod";
import { colorThemeInfoSchema } from "@repo/moss-theme";
import { localeInfoSchema } from "@repo/moss-nls";
export const defaultsSchema = z.object({
  theme: colorThemeInfoSchema,
  locale: localeInfoSchema,
});

export const preferencesSchema = z.object({
  theme: colorThemeInfoSchema.optional(),
  locale: localeInfoSchema.optional(),
});
