// @ts-nocheck - File uses recursive schemas that may cause "Type instantiation is excessively deep" errors
// Generated by ts-to-zod
import { jsonValueSchema } from "@repo/moss-bindingutils";
import { z } from "zod";
import { settingScopeSchema } from "./primitives.zod";

export const batchUpdateValueOutputSchema = z.record(z.string(), z.never());

export const updateValueOutputSchema = z.record(z.string(), z.never());
export const batchGetValueInputSchema = z.object({
  scope: settingScopeSchema,
  keys: z.array(z.string()),
});

export const batchGetValueOutputSchema = z.object({
  scope: settingScopeSchema,
  values: z.record(z.string(), jsonValueSchema.nullable()),
});

export const batchRemoveValueInputSchema = z.object({
  scope: settingScopeSchema,
  keys: z.array(z.string()),
});

export const batchRemoveValueOutputSchema = z.object({
  scope: settingScopeSchema,
  values: z.record(z.string(), jsonValueSchema.nullable()),
});

export const batchUpdateValueInputSchema = z.object({
  scope: settingScopeSchema,
  values: z.record(z.string(), jsonValueSchema),
});

export const getValueInputSchema = z.object({
  scope: settingScopeSchema,
  key: z.string(),
});

export const getValueOutputSchema = z.object({
  scope: settingScopeSchema,
  key: z.string(),
  value: jsonValueSchema,
});

export const removeValueInputSchema = z.object({
  scope: settingScopeSchema,
  key: z.string(),
});

export const removeValueOutputSchema = z.object({
  scope: settingScopeSchema,
  key: z.string(),
  value: jsonValueSchema,
});

export const updateValueInputSchema = z.object({
  scope: settingScopeSchema,
  key: z.string(),
  value: jsonValueSchema,
});
