// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import { JsonValue } from "@repo/moss-bindingutils";
import type { SettingScope } from "./primitives";

/**
 * @category Operation
 */
export type BatchGetValueInput = { scope: SettingScope; keys: Array<string> };

/**
 * @category Operation
 */
export type BatchGetValueOutput = { scope: SettingScope; values: { [key: string]: JsonValue | null } };

/**
 * @category Operation
 */
export type BatchRemoveValueInput = { scope: SettingScope; keys: Array<string> };

/**
 * @category Operation
 */
export type BatchRemoveValueOutput = { scope: SettingScope; values: { [key: string]: JsonValue | null } };

/**
 * @category Operation
 */
export type BatchUpdateValueInput = { scope: SettingScope; values: { [key: string]: JsonValue } };

/**
 * @category Operation
 */
export type BatchUpdateValueOutput = Record<string, never>;

/**
 * @category Operation
 */
export type GetValueInput = { scope: SettingScope; key: string };

/**
 * @category Operation
 */
export type GetValueOutput = { scope: SettingScope; key: string; value: JsonValue };

/**
 * @category Operation
 */
export type RemoveValueInput = { scope: SettingScope; key: string };

/**
 * @category Operation
 */
export type RemoveValueOutput = { scope: SettingScope; key: string; value: JsonValue };

/**
 * @category Operation
 */
export type UpdateValueInput = { scope: SettingScope; key: string; value: JsonValue };

/**
 * @category Operation
 */
export type UpdateValueOutput = Record<string, never>;
