[package]
name = "moss_patch"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio.workspace = true
jsonptr.workspace = true
json-patch.workspace = true
serde_json.workspace = true
hcl-rs.workspace = true
async-trait.workspace = true

pest = "2.8.1"
pest_derive = "2.8.1"

tree-sitter = { workspace = true }
tree-sitter-json = { workspace = true }
