[package]
name = "moss_kdl"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow.workspace = true
kdl.workspace = true
uuid.workspace = true
thiserror.workspace = true
serde_json.workspace = true
scraper.workspace = true
xml-rs.workspace = true
