[package]
name = "moss_nls"
version = "0.1.0"
edition = "2021"

[dependencies]
moss_app.workspace = true
moss_fs.workspace = true
ts-rs.workspace = true
serde = { workspace = true, features = ["derive"] }
tokio.workspace = true
anyhow.workspace = true
serde_json.workspace = true
