[package]
name = "moss_workspacelib"
version = "0.1.0"
edition = "2024"

[dependencies]
moss_applib = { workspace = true }
moss_environment = { workspace = true }

derive_more = { workspace = true, features = ["deref"] }
tokio = { workspace = true }
