PRAGMA foreign_keys=ON;

CREATE TABLE IF NOT EXISTS kv (
  key   TEXT PRIMARY KEY ON CONFLICT REPLACE,
  value BLOB NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_key ON kv (key);

PRAGMA user_version = 1;