[package]
name = "hcl_greeter"
version = "0.1.0"
edition = "2024"

[dependencies]
wit-bindgen-rt = { version = "0.43.0", features = ["bitflags"] }

[lib]
crate-type = ["cdylib"]

[package.metadata.component]
package = "plugin:hcl-greeter"

[package.metadata.component.target.dependencies]
# Relative path to the "wit" folder
"plugin:base" = { path = "../../../crates/moss-wasm/wit" }
