// Generated by ts-to-zod
import { z } from "zod";
import { afterUpdateDirResourceDescriptionSchema, afterUpdateItemResourceDescriptionSchema } from "./types.zod";
export const batchUpdateResourceEventSchema = z.union([
  z.object({
    "ITEM": afterUpdateItemResourceDescriptionSchema,
  }),
  z.object({
    "DIR": afterUpdateDirResourceDescriptionSchema,
  }),
]);
