// Generated by ts-to-zod
import { z } from "zod";
import { resourcePathSchema } from "./main/types.zod";
import { resourceClassSchema, resourceKindSchema, resourceProtocolSchema } from "./resource/primitives.zod";
import { afterUpdateDirResourceDescriptionSchema, afterUpdateItemResourceDescriptionSchema } from "./types.zod";
export const batchUpdateResourceEventSchema = z.union([
  z.object({
    "ITEM": afterUpdateItemResourceDescriptionSchema,
  }),
  z.object({
    "DIR": afterUpdateDirResourceDescriptionSchema,
  }),
]);

export const streamResourcesEventSchema = z.object({
  id: z.string(),
  name: z.string(),
  path: resourcePathSchema,
  class: resourceClassSchema,
  kind: resourceKindSchema,
  protocol: resourceProtocolSchema.optional(),
});
