// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ResourcePath } from "./main/types";
import type { ResourceClass, ResourceKind, ResourceProtocol } from "./resource/primitives";
import type { AfterUpdateDirResourceDescription, AfterUpdateItemResourceDescription } from "./types";

/**
 * @category Event
 */
export type BatchUpdateResourceEvent =
  | { "ITEM": AfterUpdateItemResourceDescription }
  | { "DIR": AfterUpdateDirResourceDescription };

/**
 * @category Event
 */
export type StreamResourcesEvent = {
  /**
   * Unique identifier for this resource
   */
  id: string;
  /**
   * Display name of the resource
   */
  name: string;
  /**
   * Path relative to the project root.
   * Includes both the original path string and its segments.
   */
  path: ResourcePath;
  /**
   * Classification of the resource (Endpoint, Component, or Schema)
   */
  class: ResourceClass;
  /**
   * Type of resource indicating its structure (Dir for directories, Item for files, Case of item cases)
   */
  kind: ResourceKind;
  /**
   * HTTP protocol/method used by this resource, if applicable (GET, POST, PUT, DELETE, WebSocket, GraphQL, gRPC)
   */
  protocol?: ResourceProtocol;
};
