// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ResourceClass, ResourceKind, ResourcePath, ResourceProtocol } from "./primitives";
import type { AfterUpdateDirResourceDescription, AfterUpdateItemResourceDescription } from "./types";

/**
 * @category Event
 */
export type BatchUpdateResourceEvent =
  | { "ITEM": AfterUpdateItemResourceDescription }
  | { "DIR": AfterUpdateDirResourceDescription };

/**
 * @category Event
 */
export type StreamResourcesEvent = {
  /**
   * Unique identifier for this resource
   */
  id: string;
  /**
   * Display name of the resource
   */
  name: string;
  /**
   * Path relative to the project root.
   * Includes both the original path string and its segments.
   */
  path: ResourcePath;
  /**
   * Classification of the resource (Endpoint, Component, or Schema)
   */
  class: ResourceClass;
  /**
   * Type of resource indicating its structure (Dir for directories, Item for files, Case of item cases)
   */
  kind: ResourceKind;
  /**
   * HTTP protocol/method used by this resource, if applicable (GET, POST, PUT, DELETE, WebSocket, GraphQL, gRPC)
   */
  protocol?: ResourceProtocol;
  /**
   * Determines the display position of this resource among others in the same group.
   * Resources are sorted in ascending order; lower values appear before higher ones.
   * Negative values are allowed and will be placed before positive values.
   * If multiple resources have the same order, they are sorted alphabetically.
   * If not specified, the resource appears last and is sorted alphabetically
   * among unspecified items.
   */
  order?: number;
  /**
   * Whether this resource is expanded in the tree view (applies to directories)
   */
  expanded: boolean;
};
