// Generated by ts-to-zod
import { z } from "zod";
import { entryClassSchema, entryKindSchema, entryProtocolSchema } from "./primitives.zod";
import {
  afterUpdateDirEntryDescriptionSchema,
  afterUpdateItemEntryDescriptionSchema,
  createDirEntryParamsSchema,
  createItemEntryParamsSchema,
  headerInfoSchema,
  pathParamInfoSchema,
  queryParamInfoSchema,
  updateDirEntryParamsSchema,
  updateItemEntryParamsSchema,
  vcsOperationSchema,
} from "./types.zod";

export const batchCreateEntryOutputSchema = z.object({
  ids: z.array(z.string()),
});

export const batchUpdateEntryOutputSchema = z.record(z.string(), z.never());

export const createEntryOutputSchema = z.object({
  id: z.string(),
});

export const deleteEntryInputSchema = z.object({
  id: z.string(),
});

export const deleteEntryOutputSchema = z.object({
  id: z.string(),
});

export const describeEntryInputSchema = z.object({
  id: z.string(),
});

export const executeVcsOperationOutputSchema = z.record(z.string(), z.never());

export const streamEntriesInputSchema = z.union([
  z.literal("LOAD_ROOT"),
  z.object({
    "RELOAD_PATH": z.string(),
  }),
]);

export const streamEntriesOutputSchema = z.record(z.string(), z.never());
export const batchCreateEntryKindSchema = z.union([
  z.object({
    "ITEM": createItemEntryParamsSchema,
  }),
  z.object({
    "DIR": createDirEntryParamsSchema,
  }),
]);

export const batchUpdateEntryKindSchema = z.union([
  z.object({
    "ITEM": updateItemEntryParamsSchema,
  }),
  z.object({
    "DIR": updateDirEntryParamsSchema,
  }),
]);

export const batchUpdateEntryOutputKindSchema = z.union([
  z.object({
    "ITEM": afterUpdateItemEntryDescriptionSchema,
  }),
  z.object({
    "DIR": afterUpdateDirEntryDescriptionSchema,
  }),
]);

export const createEntryInputSchema = z.union([
  z.object({
    "ITEM": createItemEntryParamsSchema,
  }),
  z.object({
    "DIR": createDirEntryParamsSchema,
  }),
]);

export const describeEntryOutputSchema = z.object({
  name: z.string(),
  class: entryClassSchema,
  kind: entryKindSchema,
  protocol: entryProtocolSchema.optional(),
  url: z.string().optional(),
  headers: z.array(headerInfoSchema),
  pathParams: z.array(pathParamInfoSchema),
  queryParams: z.array(queryParamInfoSchema),
});

export const executeVcsOperationInputSchema = z.object({
  operation: vcsOperationSchema,
});

export const updateEntryInputSchema = z.union([
  z.object({
    "ITEM": updateItemEntryParamsSchema,
  }),
  z.object({
    "DIR": updateDirEntryParamsSchema,
  }),
]);

export const updateEntryOutputSchema = z.union([
  z.object({
    "ITEM": afterUpdateItemEntryDescriptionSchema,
  }),
  z.object({
    "DIR": afterUpdateDirEntryDescriptionSchema,
  }),
]);

export const batchCreateEntryInputSchema = z.object({
  entries: z.array(batchCreateEntryKindSchema),
});

export const batchUpdateEntryInputSchema = z.object({
  entries: z.array(batchUpdateEntryKindSchema),
});
