// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ResourceClass, ResourceKind, ResourceProtocol } from "./primitives";
import type {
  AfterCreateResourceDescription,
  AfterUpdateDirResourceDescription,
  AfterUpdateItemResourceDescription,
  BodyInfo,
  CreateDirResourceParams,
  CreateItemResourceParams,
  HeaderInfo,
  PathParamInfo,
  QueryParamInfo,
  UpdateDirResourceParams,
  UpdateItemResourceParams,
  VcsOperation,
} from "./types";

/**
 * @category Operation
 */
export type BatchCreateResourceInput = { resources: Array<BatchCreateResourceKind> };

/**
 * @category Operation
 */
export type BatchCreateResourceKind = { "ITEM": CreateItemResourceParams } | { "DIR": CreateDirResourceParams };

/**
 * @category Operation
 */
export type BatchCreateResourceOutput = { resources: Array<AfterCreateResourceDescription> };

/**
 * @category Operation
 */
export type BatchUpdateResourceInput = { resources: Array<BatchUpdateResourceKind> };

/**
 * @category Operation
 */
export type BatchUpdateResourceKind = { "ITEM": UpdateItemResourceParams } | { "DIR": UpdateDirResourceParams };

/**
 * @category Operation
 */
export type BatchUpdateResourceOutput = Record<string, never>;

/**
 * @category Operation
 */
export type BatchUpdateResourceOutputKind =
  | { "ITEM": AfterUpdateItemResourceDescription }
  | { "DIR": AfterUpdateDirResourceDescription };

/**
 * @category Operation
 */
export type CreateResourceInput = { "ITEM": CreateItemResourceParams } | { "DIR": CreateDirResourceParams };

/**
 * @category Operation
 */
export type CreateResourceOutput = { id: string };

/**
 * @category Operation
 */
export type DeleteResourceInput = { id: string };

/**
 * @category Operation
 */
export type DeleteResourceOutput = { id: string };

export type DescribeResourceOutput = {
  name: string;
  class: ResourceClass;
  kind: ResourceKind;
  protocol?: ResourceProtocol;
  url?: string;
  headers: Array<HeaderInfo>;
  pathParams: Array<PathParamInfo>;
  queryParams: Array<QueryParamInfo>;
  body?: BodyInfo;
};

/**
 * @category Operation
 */
export type ExecuteVcsOperationInput = { operation: VcsOperation };

/**
 * @category Operation
 */
export type ExecuteVcsOperationOutput = Record<string, never>;

/**
 * @category Operation
 */
export type StreamResourcesInput = "LOAD_ROOT" | { "RELOAD_PATH": string };

/**
 * @category Operation
 */
export type StreamResourcesOutput = Record<string, never>;

/**
 * @category Operation
 */
export type UpdateResourceInput = { "ITEM": UpdateItemResourceParams } | { "DIR": UpdateDirResourceParams };

/**
 * @category Operation
 */
export type UpdateResourceOutput =
  | { "ITEM": AfterUpdateItemResourceDescription }
  | { "DIR": AfterUpdateDirResourceDescription };
