// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type {
  AfterUpdateDirEntryDescription,
  AfterUpdateItemEntryDescription,
  CreateDirEntryParams,
  CreateItemEntryParams,
  UpdateDirEntryParams,
  UpdateItemEntryParams,
  VcsOperation,
} from "./types";

/**
 * @category Operation
 */
export type BatchCreateEntryInput = { entries: Array<BatchCreateEntryKind> };

/**
 * @category Operation
 */
export type BatchCreateEntryKind = { "ITEM": CreateItemEntryParams } | { "DIR": CreateDirEntryParams };

/**
 * @category Operation
 */
export type BatchCreateEntryOutput = { ids: Array<string> };

/**
 * @category Operation
 */
export type BatchUpdateEntryInput = { entries: Array<BatchUpdateEntryKind> };

/**
 * @category Operation
 */
export type BatchUpdateEntryKind = { "ITEM": UpdateItemEntryParams } | { "DIR": UpdateDirEntryParams };

/**
 * @category Operation
 */
export type BatchUpdateEntryOutput = Record<string, never>;

/**
 * @category Operation
 */
export type BatchUpdateEntryOutputKind =
  | { "ITEM": AfterUpdateItemEntryDescription }
  | { "DIR": AfterUpdateDirEntryDescription };

/**
 * @category Operation
 */
export type CreateEntryInput = { "ITEM": CreateItemEntryParams } | { "DIR": CreateDirEntryParams };

/**
 * @category Operation
 */
export type CreateEntryOutput = { id: string };

/**
 * @category Operation
 */
export type DeleteEntryInput = { id: string };

/**
 * @category Operation
 */
export type DeleteEntryOutput = { id: string };

/**
 * @category Operation
 */
export type ExecuteVcsOperationInput = { operation: VcsOperation };

/**
 * @category Operation
 */
export type ExecuteVcsOperationOutput = Record<string, never>;

/**
 * @category Operation
 */
export type StreamEntriesInput = "LOAD_ROOT" | { "RELOAD_PATH": string };

/**
 * @category Operation
 */
export type StreamEntriesOutput = Record<string, never>;

/**
 * @category Operation
 */
export type UpdateEntryInput = { "ITEM": UpdateItemEntryParams } | { "DIR": UpdateDirEntryParams };

/**
 * @category Operation
 */
export type UpdateEntryOutput = { "ITEM": AfterUpdateItemEntryDescription } | { "DIR": AfterUpdateDirEntryDescription };
