// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * @category Primitive
 */
export type EntryClass = "Endpoint" | "Component" | "Schema";

/**
 * @category Primitive
 */
export type EntryKind = "Dir" | "Item" | "Case";

/**
 * @category Primitive
 */
export type EntryPath = { raw: string; segments: Array<string> };

/**
 * @category Primitive
 */
export type EntryProtocol = "Get" | "Post" | "Put" | "Delete" | "WebSocket" | "Graphql" | "Grpc";

/**
 * @category Primitive
 */
export type HttpMethod = "GET" | "POST" | "PUT" | "DELETE";
