// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * @category Primitive
 */
export type ResourceClass = "endpoint" | "component" | "schema";

/**
 * @category Primitive
 */
export type ResourceKind = "Dir" | "Item" | "Case";

/**
 * @category Primitive
 */
export type ResourcePath = { raw: string; segments: Array<string> };

/**
 * @category Primitive
 */
export type ResourceProtocol = "Get" | "Post" | "Put" | "Delete" | "WebSocket" | "Graphql" | "Grpc";

/**
 * @category Primitive
 */
export type HttpMethod = "GET" | "POST" | "PUT" | "DELETE";
