// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import { ChangeJsonValue, ChangeString, JsonValue } from "@repo/moss-bindingutils";
import type { EntryClass, EntryPath, EntryProtocol } from "./primitives";

/**
 * @category Type
 */
export type AddHeaderParams = {
  name: string;
  value: JsonValue;
  order: number;
  desc?: string;
  options: HeaderParamOptions;
};

/**
 * @category Type
 */
export type AddPathParamParams = {
  name: string;
  value: JsonValue;
  order: number;
  desc?: string;
  options: PathParamOptions;
};

/**
 * @category Type
 */
export type AddQueryParamParams = {
  name: string;
  value: JsonValue;
  order: number;
  desc?: string;
  options: QueryParamOptions;
};

/**
 * @category Type
 */
export type AfterUpdateDirEntryDescription = { id: string; path: EntryPath };

/**
 * @category Type
 */
export type AfterUpdateItemEntryDescription = { id: string; path: EntryPath };

/**
 * @category Type
 */
export type CreateDirEntryParams = { path: string; class: EntryClass; name: string; order: number };

/**
 * @category Type
 */
export type CreateItemEntryParams = {
  path: string;
  class: EntryClass;
  name: string;
  order: number;
  protocol?: EntryProtocol;
  headers: Array<AddHeaderParams>;
  pathParams: Array<AddPathParamParams>;
  queryParams: Array<AddQueryParamParams>;
};

/**
 * @category Type
 */
export type HeaderInfo = {
  id: string;
  name: string;
  value: JsonValue;
  description: string | null;
  disabled: boolean;
  propagate: boolean;
  order: number | null;
};

/**
 * @category Type
 */
export type HeaderParamOptions = { disabled: boolean; propagate: boolean };

/**
 * @category Type
 */
export type PathParamInfo = {
  id: string;
  name: string;
  value: JsonValue;
  description: string | null;
  disabled: boolean;
  propagate: boolean;
  order: number | null;
};

/**
 * @category Type
 */
export type PathParamOptions = { disabled: boolean; propagate: boolean };

/**
 * @category Type
 */
export type QueryParamInfo = {
  id: string;
  name: string;
  value: JsonValue;
  description: string | null;
  disabled: boolean;
  propagate: boolean;
  order: number | null;
};

/**
 * @category Type
 */
export type QueryParamOptions = { disabled: boolean; propagate: boolean };

/**
 * @category Type
 */
export type UpdateDirEntryParams = {
  id: string;
  /**
   * If provided, the directory will move to the new path
   * For example, if the new path is "requests/folder/", the name is "group"
   * The new relative path of the directory folder will be "requests/folder/group"
   */
  path?: string;
  name?: string;
  order?: number;
  expanded?: boolean;
};

/**
 * @category Type
 */
export type UpdateHeaderParamOptions = { disabled?: boolean; propagate?: boolean };

/**
 * @category Type
 */
export type UpdateHeaderParams = {
  id: string;
  name?: string;
  value?: ChangeJsonValue;
  order?: number;
  desc?: ChangeString;
  options?: HeaderParamOptions;
};

/**
 * @category Type
 */
export type UpdateItemEntryParams = {
  id: string;
  /**
   * If provided, the entry will move to the new path
   * For example, if the new path is "requests/folder/", the name is "entry"
   * The new relative path of the entry folder will be "requests/folder/entry"
   */
  path?: string;
  name?: string;
  order?: number;
  expanded?: boolean;
  protocol?: EntryProtocol;
  queryParamsToAdd: Array<AddQueryParamParams>;
  queryParamsToUpdate: Array<UpdateQueryParamParams>;
  queryParamsToRemove: Array<string>;
  pathParamsToAdd: Array<AddPathParamParams>;
  pathParamsToUpdate: Array<UpdatePathParamParams>;
  pathParamsToRemove: Array<string>;
  headersToAdd: Array<AddHeaderParams>;
  headersToUpdate: Array<UpdateHeaderParams>;
  headersToRemove: Array<string>;
};

/**
 * @category Type
 */
export type UpdatePathParamOptions = { disabled?: boolean; propagate?: boolean };

/**
 * @category Type
 */
export type UpdatePathParamParams = {
  id: string;
  name?: string;
  value?: ChangeJsonValue;
  order?: number;
  desc?: ChangeString;
  options?: PathParamOptions;
};

/**
 * @category Type
 */
export type UpdateQueryParamOptions = { disabled?: boolean; propagate?: boolean };

/**
 * @category Type
 */
export type UpdateQueryParamParams = {
  id: string;
  name?: string;
  value?: ChangeJsonValue;
  order?: number;
  desc?: ChangeString;
  options?: QueryParamOptions;
};

/**
 * @category Type
 */
export type VcsOperation =
  | { "COMMIT": { message: string; paths: Array<string>; push: boolean } }
  | { "DISCARD": { paths: Array<string> } }
  | "PUSH"
  | "PULL"
  | "FETCH";
