// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import { ChangeJsonValue, ChangeString, JsonValue } from "@repo/moss-bindingutils";
import type { ResourceClass, ResourcePath, ResourceProtocol } from "./primitives";

/**
 * @category Type
 */
export type AddBodyParams =
  | { "text": string }
  | { "json": JsonValue }
  | { "xml": string }
  | { "binary": string }
  | { "urlencoded": Array<AddUrlencodedParamParams> }
  | { "formData": Array<AddFormDataParamParams> };

/**
 * @category Type
 */
export type AddFormDataParamParams = {
  name: string;
  value: JsonValue;
  order: number;
  description?: string;
  options: FormDataParamOptions;
  /**
   * This field should be provided when the frontend switches back to formdata body type
   * We will reuse the old ids to avoid unnecessary changes
   */
  id?: string;
};

/**
 * @category Type
 */
export type AddHeaderParams = {
  name: string;
  value: JsonValue;
  order: number;
  description?: string;
  options: HeaderParamOptions;
};

/**
 * @category Type
 */
export type AddPathParamParams = {
  name: string;
  value: JsonValue;
  order: number;
  description?: string;
  options: PathParamOptions;
};

/**
 * @category Type
 */
export type AddQueryParamParams = {
  name: string;
  value: JsonValue;
  order: number;
  description?: string;
  options: QueryParamOptions;
};

/**
 * @category Type
 */
export type AddUrlencodedParamParams = {
  name: string;
  value: JsonValue;
  order: number;
  description?: string;
  options: UrlencodedParamOptions;
  /**
   * This field should be provided when the frontend switches back to urlencoded body type
   * We will reuse the old ids to avoid unnecessary changes
   */
  id?: string;
};

/**
 * @category Type
 */
export type AfterUpdateDirResourceDescription = { id: string; path: ResourcePath };

/**
 * @category Type
 */
export type AfterUpdateItemResourceDescription = { id: string; path: ResourcePath };

/**
 * @category Type
 */
export type BodyInfo =
  | { "text": string }
  | { "json": JsonValue }
  | { "xml": string }
  | { "binary": string }
  | { "urlencoded": Array<UrlencodedParamInfo> }
  | { "formData": Array<FormDataParamInfo> };

/**
 * @category Type
 */
export type CreateDirResourceParams = { path: string; class: ResourceClass; name: string; order: number };

/**
 * @category Type
 */
export type CreateItemResourceParams = {
  path: string;
  class: ResourceClass;
  name: string;
  order: number;
  protocol?: ResourceProtocol;
  url?: string;
  headers: Array<AddHeaderParams>;
  pathParams: Array<AddPathParamParams>;
  queryParams: Array<AddQueryParamParams>;
  body?: AddBodyParams;
};

/**
 * @category Type
 */
export type FormDataParamInfo = {
  id: string;
  name: string;
  value: JsonValue;
  description?: string;
  disabled: boolean;
  propagate: boolean;
  order?: number;
};

/**
 * @category Type
 */
export type FormDataParamOptions = { disabled: boolean; propagate: boolean };

/**
 * @category Type
 */
export type HeaderInfo = {
  id: string;
  name: string;
  value: JsonValue;
  description?: string;
  disabled: boolean;
  propagate: boolean;
  order?: number;
};

/**
 * @category Type
 */
export type HeaderParamOptions = { disabled: boolean; propagate: boolean };

/**
 * @category Type
 */
export type PathParamInfo = {
  id: string;
  name: string;
  value: JsonValue;
  description?: string;
  disabled: boolean;
  propagate: boolean;
  order?: number;
};

/**
 * @category Type
 */
export type PathParamOptions = { disabled: boolean; propagate: boolean };

/**
 * @category Type
 */
export type QueryParamInfo = {
  id: string;
  name: string;
  value: JsonValue;
  description?: string;
  disabled: boolean;
  propagate: boolean;
  order?: number;
};

/**
 * @category Type
 */
export type QueryParamOptions = { disabled: boolean; propagate: boolean };

/**
 * @category Type
 */
export type UpdateBodyParams =
  | "remove"
  | { "text": string }
  | { "json": JsonValue }
  | { "xml": string }
  | { "binary": string }
  | {
      "urlencoded": {
        params_to_add: Array<AddUrlencodedParamParams>;
        params_to_update: Array<UpdateUrlencodedParamParams>;
        params_to_remove: Array<string>;
      };
    }
  | {
      "formData": {
        params_to_add: Array<AddFormDataParamParams>;
        params_to_update: Array<UpdateFormDataParamParams>;
        params_to_remove: Array<string>;
      };
    };

/**
 * @category Type
 */
export type UpdateDirResourceParams = {
  id: string;
  /**
   * If provided, the directory will move to the new path
   * For example, if the new path is "requests/folder/", the name is "group"
   * The new relative path of the directory folder will be "requests/folder/group"
   */
  path?: string;
  name?: string;
  order?: number;
  expanded?: boolean;
};

/**
 * @category Type
 */
export type UpdateFormDataParamParams = {
  id: string;
  name?: string;
  value?: ChangeJsonValue;
  order?: number;
  description?: ChangeString;
  options?: FormDataParamOptions;
};

/**
 * @category Type
 */
export type UpdateHeaderParamOptions = { disabled?: boolean; propagate?: boolean };

/**
 * @category Type
 */
export type UpdateHeaderParams = {
  id: string;
  name?: string;
  value?: ChangeJsonValue;
  order?: number;
  description?: ChangeString;
  options?: HeaderParamOptions;
};

/**
 * @category Type
 */
export type UpdateItemResourceParams = {
  id: string;
  /**
   * If provided, the resource will move to the new path
   * For example, if the new path is "requests/folder/", the name is "resource"
   * The new relative path of the resource folder will be "requests/folder/resource"
   */
  path?: string;
  name?: string;
  order?: number;
  expanded?: boolean;
  protocol?: ResourceProtocol;
  url?: string;
  headersToAdd: Array<AddHeaderParams>;
  headersToUpdate: Array<UpdateHeaderParams>;
  headersToRemove: Array<string>;
  pathParamsToAdd: Array<AddPathParamParams>;
  pathParamsToUpdate: Array<UpdatePathParamParams>;
  pathParamsToRemove: Array<string>;
  queryParamsToAdd: Array<AddQueryParamParams>;
  queryParamsToUpdate: Array<UpdateQueryParamParams>;
  queryParamsToRemove: Array<string>;
  body?: UpdateBodyParams;
};

/**
 * @category Type
 */
export type UpdatePathParamOptions = { disabled?: boolean; propagate?: boolean };

/**
 * @category Type
 */
export type UpdatePathParamParams = {
  id: string;
  name?: string;
  value?: ChangeJsonValue;
  order?: number;
  description?: ChangeString;
  options?: PathParamOptions;
};

/**
 * @category Type
 */
export type UpdateQueryParamOptions = { disabled?: boolean; propagate?: boolean };

/**
 * @category Type
 */
export type UpdateQueryParamParams = {
  id: string;
  name?: string;
  value?: ChangeJsonValue;
  order?: number;
  description?: ChangeString;
  options?: QueryParamOptions;
};

/**
 * @category Type
 */
export type UpdateUrlencodedParamParams = {
  id: string;
  name?: string;
  value?: ChangeJsonValue;
  order?: number;
  description?: ChangeString;
  options?: UrlencodedParamOptions;
};

/**
 * @category Type
 */
export type UrlencodedParamInfo = {
  id: string;
  name: string;
  value: JsonValue;
  description?: string;
  disabled: boolean;
  propagate: boolean;
  order?: number;
};

/**
 * @category Type
 */
export type UrlencodedParamOptions = { disabled: boolean; propagate: boolean };

/**
 * @category Type
 */
export type VcsOperation =
  | { "COMMIT": { message: string; paths: Array<string>; push: boolean } }
  | { "DISCARD": { paths: Array<string> } }
  | "PUSH"
  | "PULL"
  | "FETCH";
