import { useEffect, useState } from "react";
import { ChatOllama } from "@langchain/ollama";
import { createReactAgent } from "@langchain/langgraph/prebuilt";
import { tool } from "@langchain/core/tools";
import { z } from "zod";

async function setupAgent() {
  // Running a test model locally using Ollama
  const llm = new ChatOllama({ model: "qwen3:4b" });

  const alertSchema = z.object({
    message: z.string().describe("Message to be shown in the alert popup"),
  });

  const alertTool = tool(
    async ({ message }) => {
      alert(message);
      return "Successfully sent an alert popup";
    },
    {
      name: "alert",
      description: "Send an alert popup with a given message.",
      schema: alertSchema,
    }
  );

  const agent = createReactAgent({ llm, tools: [alertTool] });
  return agent;
}

function useAgent() {
  const [agent, setAgent] = useState<any>(null);
  useEffect(() => {
    setupAgent().then((agent) => {
      setAgent(agent);
    });
  }, []);
  return agent;
}

const LangchainAgent = () => {
  const agent = useAgent();

  function handleClick() {
    const prompt = `Please send an alert popup with the following message: "This alert popup is generated by the agent"`;
    agent
      .invoke({
        messages: [{ role: "user", content: prompt }],
      })
      .then((response) => console.log(response));
  }

  return (
    <div>
      <button className="cursor-pointer rounded bg-green-500 p-2 text-white hover:bg-green-600" onClick={handleClick}>
        Test prompt
      </button>
    </div>
  );
};

export default LangchainAgent;
