// Generated by ts-to-zod
import { jsonValueSchema } from "@repo/moss-bindingutils";
import { z } from "zod";
import { logLevelSchema, themeIdSchema } from "./primitives.zod";
export const colorThemeChangeEventPayloadSchema = z.object({
  id: themeIdSchema,
});

export const onDidAppendLogEntrySchema = z.object({
  id: z.string(),
  timestamp: z.string(),
  level: logLevelSchema,
  resource: z.string().optional(),
  message: z.string(),
});

export const onDidChangeConfigurationSchema = z.object({
  affected_keys: z.array(z.string()),
  changes: z.record(z.string(), jsonValueSchema),
});
