// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import { JsonValue } from "@repo/bindings-utils";
import type { ColorThemeInfo, Defaults, LocaleInfo, Preferences } from "./types";

export type DescribeAppStateOutput = { preferences: Preferences; defaults: Defaults; lastWorkspace?: string };

export type GetColorThemeInput = { id: string };

export type GetColorThemeOutput = { cssContent: string };

export type GetTranslationsInput = { language: string; namespace: string };

export type GetTranslationsOutput = JsonValue;

export type ListColorThemesOutput = Array<ColorThemeInfo>;

export type ListLocalesOutput = Array<LocaleInfo>;

export type SetColorThemeInput = { themeInfo: ColorThemeInfo };

export type SetLocaleInput = { localeInfo: LocaleInfo };
