// Generated by ts-to-zod
import { z } from "zod";

export const logLevelSchema = z.union([
  z.literal("TRACE"),
  z.literal("DEBUG"),
  z.literal("INFO"),
  z.literal("WARN"),
  z.literal("ERROR"),
]);
