// Generated by ts-to-zod
import { z } from "zod";

export const gitProviderTypeSchema = z.union([z.literal("GitHub"), z.literal("GitLab")]);

export const logLevelSchema = z.union([
  z.literal("TRACE"),
  z.literal("DEBUG"),
  z.literal("INFO"),
  z.literal("WARN"),
  z.literal("ERROR"),
]);

export const themeModeSchema = z.union([z.literal("light"), z.literal("dark")]);
