// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LogLevel, ThemeMode } from "./primitives";

export type ColorThemeInfo = {
  identifier: string;
  displayName: string;
  mode: ThemeMode;
  order?: number;
  source: string;
  isDefault?: boolean;
};

export type Defaults = { theme: ColorThemeInfo; locale: LocaleInfo };

export type LocaleInfo = {
  identifier: string;
  displayName: string;
  code: string;
  direction?: string;
  isDefault?: boolean;
};

export type LogDate = { year: number; month: number; day: number };

export type LogEntryInfo = {
  id: string;
  /**
   * A timestamp string, such as "2025-06-06T19:26:39.084+0300"
   */
  timestamp: string;
  level: LogLevel;
  resource?: string;
  message: string;
};

export type LogItemSourceInfo = { id: string };

export type Preferences = { theme: ColorThemeInfo | null; locale: LocaleInfo | null };
