// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import { JsonValue } from "@repo/moss-bindingutils";
import type {
  AccountKind,
  ConfigurationParameterType,
  ConfigurationTarget,
  LogLevel,
  ThemeId,
  ThemeMode,
} from "./primitives";

/**
 * @category Type
 */
export type AddAccountParams = {
  host: string;
  label?: string;
  kind: AccountKind;
  /**
   * If a PAT is not provided, we will use OAuth
   */
  pat?: string;
};

/**
 * @category Type
 */
export type ColorThemeInfo = {
  identifier: ThemeId;
  displayName: string;
  mode: ThemeMode;
  order?: number;
  source: string;
  isDefault?: boolean;
};

/**
 * @category Type
 */
export type Configuration = { keys: Array<string>; contents: { [key: string]: JsonValue } };

/**
 * @category Type
 */
export type ConfigurationSchema = {
  id: string;
  parentId?: string;
  order?: bigint;
  name?: string;
  description?: string;
  parameters: Array<ParameterSchema>;
};

/**
 * @category Type
 */
export type LocaleInfo = {
  identifier: string;
  displayName: string;
  code: string;
  direction?: string;
  order?: number;
  isDefault?: boolean;
};

/**
 * @category Type
 */
export type LogDate = { year: number; month: number; day: number };

/**
 * @category Type
 */
export type LogEntryInfo = {
  id: string;
  /**
   * A timestamp string, such as "2025-06-06T19:26:39.084+0300"
   */
  timestamp: string;
  level: LogLevel;
  resource?: string;
  message: string;
};

/**
 * @category Type
 */
export type LogItemSourceInfo = { id: string };

/**
 * @category Type
 */
export type ParameterSchema = {
  id: string;
  default?: JsonValue;
  typ: ConfigurationParameterType;
  description?: string;
  maximum?: bigint;
  minimum?: bigint;
  protected: boolean;
  order?: bigint;
  tags: Array<string>;
};

/**
 * @category Type
 */
export type UpdateConfigurationParams = { key: string; value: JsonValue; target: ConfigurationTarget };

/**
 * @category Type
 */
export type WorkspaceInfo = { id: string; name: string; lastOpenedAt?: bigint };
