// Generated by ts-to-zod
import { z } from "zod";
import { logLevelSchema, themeModeSchema } from "./primitives.zod";

export const localeInfoSchema = z.object({
  identifier: z.string(),
  displayName: z.string(),
  code: z.string(),
  direction: z.string().optional(),
  isDefault: z.boolean().optional(),
});

export const logDateSchema = z.object({
  year: z.number(),
  month: z.number(),
  day: z.number(),
});

export const logItemSourceInfoSchema = z.object({
  id: z.string(),
});
export const colorThemeInfoSchema = z.object({
  identifier: z.string(),
  displayName: z.string(),
  mode: themeModeSchema,
  order: z.number().optional(),
  source: z.string(),
  isDefault: z.boolean().optional(),
});

export const defaultsSchema = z.object({
  theme: colorThemeInfoSchema,
  locale: localeInfoSchema,
});

export const logEntryInfoSchema = z.object({
  id: z.string(),
  timestamp: z.string(),
  level: logLevelSchema,
  resource: z.string().optional(),
  message: z.string(),
});

export const preferencesSchema = z.object({
  theme: colorThemeInfoSchema.nullable(),
  locale: localeInfoSchema.nullable(),
});
