// Generated by ts-to-zod
import { jsonValueSchema } from "@repo/moss-bindingutils";
import { z } from "zod";
import { accountKindSchema, configurationTargetSchema, logLevelSchema, themeModeSchema } from "./primitives.zod";

export const localeInfoSchema = z.object({
  identifier: z.string(),
  displayName: z.string(),
  code: z.string(),
  direction: z.string().optional(),
  order: z.number().optional(),
  isDefault: z.boolean().optional(),
});

export const logDateSchema = z.object({
  year: z.number(),
  month: z.number(),
  day: z.number(),
});

export const logItemSourceInfoSchema = z.object({
  id: z.string(),
});

export const workspaceInfoSchema = z.object({
  id: z.string(),
  name: z.string(),
  lastOpenedAt: z.bigint().optional(),
});
export const addAccountParamsSchema = z.object({
  host: z.string(),
  label: z.string().optional(),
  kind: accountKindSchema,
  pat: z.string().optional(),
});

export const colorThemeInfoSchema = z.object({
  identifier: z.string(),
  displayName: z.string(),
  mode: themeModeSchema,
  order: z.number().optional(),
  source: z.string(),
  isDefault: z.boolean().optional(),
});

export const configurationSchema = z.object({
  keys: z.array(z.string()),
  contents: z.record(z.string(), jsonValueSchema),
});

export const logEntryInfoSchema = z.object({
  id: z.string(),
  timestamp: z.string(),
  level: logLevelSchema,
  resource: z.string().optional(),
  message: z.string(),
});

export const updateConfigurationParamsSchema = z.object({
  key: z.string(),
  value: jsonValueSchema,
  target: configurationTargetSchema,
});
