#!/bin/sh

prettier --plugin=prettier-plugin-tailwindcss --write \"**/*.{ts,tsx,md}\"

if [ $? -ne 0 ]; then
  echo "Linting failed. Aborting commit."
  exit 1
fi

git add .

# git commit -m "chore: auto-format code"

exit 0
