[package]
name = "moss_collection"
version = "0.1.0"
edition = "2021"

[dependencies]
moss_fs.workspace = true
moss_app.workspace = true
moss_db.workspace = true
anyhow.workspace = true
kdl.workspace = true
serde = { workspace = true, features = ["derive"] }
thiserror.workspace = true
miette = { workspace = true, features = ["fancy"] }
sled.workspace = true
bincode.workspace = true
dashmap.workspace = true
tokio.workspace = true
async-trait.workspace = true
patricia_tree.workspace = true
parking_lot.workspace = true
ts-rs = { workspace = true, features = ["serde-json-impl"] }
serde_json.workspace = true
arc-swap.workspace = true
html5ever.workspace = true
scraper.workspace = true
xml-rs.workspace = true

[dev-dependencies]
mockall = "0.13.1"
