// Generated by ts-to-zod
import { z } from "zod";
import { parsedUrlSchema } from "./types.zod";

export const parseUrlInputSchema = z.object({
  url: z.string(),
});
export const parseUrlOutputSchema = parsedUrlSchema;
