// Generated by ts-to-zod
import { z } from "zod";

export const parsedValueSchema = z.union([
  z.object({
    "string": z.string(),
  }),
  z.object({
    "variable": z.string(),
  }),
  z.object({
    "pathVariable": z.string(),
  }),
]);

export const queryParamSchema = z.object({
  key: z.array(parsedValueSchema),
  value: z.array(parsedValueSchema).optional(),
});

export const parsedUrlSchema = z.object({
  schemePart: z.array(parsedValueSchema),
  hostPart: z.array(parsedValueSchema),
  pathPart: z.array(parsedValueSchema),
  queryPart: z.array(queryParamSchema),
  fragmentPart: z.array(parsedValueSchema).optional(),
  raw: z.array(parsedValueSchema),
});
