// Generated by ts-to-zod
import { z } from "zod";
import { entryClassSchema, entryKindSchema, entryPathSchema, entryProtocolSchema } from "./primitives.zod";
import { afterUpdateDirEntryDescriptionSchema, afterUpdateItemEntryDescriptionSchema } from "./types.zod";
export const batchUpdateEntryEventSchema = z.union([
  z.object({
    "ITEM": afterUpdateItemEntryDescriptionSchema,
  }),
  z.object({
    "DIR": afterUpdateDirEntryDescriptionSchema,
  }),
]);

export const streamEntriesEventSchema = z.object({
  id: z.string(),
  name: z.string(),
  path: entryPathSchema,
  class: entryClassSchema,
  kind: entryKindSchema,
  protocol: entryProtocolSchema.nullable(),
  order: z.number().nullable(),
  expanded: z.boolean(),
});
