// Generated by ts-to-zod
import { z } from "zod";
import {
  afterUpdateDirEntryDescriptionSchema,
  afterUpdateItemEntryDescriptionSchema,
  entryInfoSchema,
} from "./types.zod";
export const batchUpdateEntryEventSchema = z.union([
  z.object({
    "ITEM": afterUpdateItemEntryDescriptionSchema,
  }),
  z.object({
    "DIR": afterUpdateDirEntryDescriptionSchema,
  }),
]);

export const streamEntriesEventSchema = entryInfoSchema;
