// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AfterUpdateDirEntryDescription, AfterUpdateItemEntryDescription, EntryInfo } from "./types";

/**
 * @category Event
 */
export type BatchUpdateEntryEvent =
  | { "ITEM": AfterUpdateItemEntryDescription }
  | { "DIR": AfterUpdateDirEntryDescription };

/**
 * @category Event
 */
export type StreamEntriesEvent = EntryInfo;
