// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AfterUpdateDirEntryDescription, AfterUpdateItemEntryDescription, EntryInfo } from "./types";

export type BatchUpdateEntryEvent =
  | { "Item": AfterUpdateItemEntryDescription }
  | { "Dir": AfterUpdateDirEntryDescription };

export type StreamEntriesEvent = EntryInfo;
