// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EntryClass, EntryKind, EntryPath, EntryProtocol } from "./primitives";
import type { AfterUpdateDirEntryDescription, AfterUpdateItemEntryDescription } from "./types";

/**
 * @category Event
 */
export type BatchUpdateEntryEvent =
  | { "ITEM": AfterUpdateItemEntryDescription }
  | { "DIR": AfterUpdateDirEntryDescription };

/**
 * @category Event
 */
export type StreamEntriesEvent = {
  /**
   * Unique identifier for this entry
   */
  id: string;
  /**
   * Display name of the entry
   */
  name: string;
  /**
   * Path relative to the collection root.
   * Includes both the original path string and its segments.
   */
  path: EntryPath;
  /**
   * Classification of the entry (Request, Endpoint, Component, or Schema)
   */
  class: EntryClass;
  /**
   * Type of entry indicating its structure (Dir for directories, Item for files, Case of item cases)
   */
  kind: EntryKind;
  /**
   * HTTP protocol/method used by this entry, if applicable (GET, POST, PUT, DELETE, WebSocket, GraphQL, gRPC)
   */
  protocol: EntryProtocol | null;
  /**
   * Determines the display position of this entry among others in the same group.
   * Entries are sorted in ascending order; lower values appear before higher ones.
   * Negative values are allowed and will be placed before positive values.
   * If multiple entries have the same order, they are sorted alphabetically.
   * If not specified, the entry appears last and is sorted alphabetically
   * among unspecified items.
   */
  order: number | null;
  /**
   * Whether this entry is expanded in the tree view (applies to directories)
   */
  expanded: boolean;
};
