// Generated by ts-to-zod
import { z } from "zod";
import { entryPathSchema, entryProtocolSchema } from "./primitives.zod";
import {
  compositeDirConfigurationModelSchema,
  compositeItemConfigurationModelSchema,
  dirConfigurationModelSchema,
  itemConfigurationModelSchema,
} from "./types.zod";

export const createEntryOutputSchema = z.object({
  id: z.string(),
});

export const deleteEntryInputSchema = z.object({
  id: z.string(),
});

export const deleteEntryOutputSchema = z.object({
  id: z.string(),
});

export const streamEntriesOutputSchema = z.record(z.never());

export const updateDirEntryInputSchema = z.object({
  id: z.string(),
  path: z.string(),
  name: z.string().optional(),
  order: z.number().optional(),
  expanded: z.boolean().optional(),
});
export const createDirEntryInputSchema = z.object({
  path: z.string(),
  name: z.string(),
  order: z.number(),
  configuration: dirConfigurationModelSchema,
});

export const createItemEntryInputSchema = z.object({
  path: z.string(),
  name: z.string(),
  order: z.number(),
  configuration: itemConfigurationModelSchema,
});

export const updateDirEntryOutputSchema = z.object({
  ID: z.string(),
  PATH: entryPathSchema,
  CONFIGURATION: compositeDirConfigurationModelSchema,
});

export const updateItemEntryInputSchema = z.object({
  id: z.string(),
  path: z.string(),
  name: z.string().optional(),
  protocol: entryProtocolSchema.optional(),
  order: z.number().optional(),
  expanded: z.boolean().optional(),
});

export const updateItemEntryOutputSchema = z.object({
  ID: z.string(),
  PATH: entryPathSchema,
  CONFIGURATION: compositeItemConfigurationModelSchema,
});

export const createEntryInputSchema = z.union([
  z.object({
    "item": createItemEntryInputSchema,
  }),
  z.object({
    "dir": createDirEntryInputSchema,
  }),
]);

export const updateEntryInputSchema = z.union([
  z.object({
    "ITEM": updateItemEntryInputSchema,
  }),
  z.object({
    "DIR": updateDirEntryInputSchema,
  }),
]);

export const updateEntryOutputSchema = z.union([
  z.object({
    "ITEM": updateItemEntryOutputSchema,
  }),
  z.object({
    "DIR": updateDirEntryOutputSchema,
  }),
]);
