// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EntryPath, EntryProtocol } from "./primitives";
import type {
  CompositeDirConfigurationModel,
  CompositeItemConfigurationModel,
  DirConfigurationModel,
  ItemConfigurationModel,
} from "./types";

export type CreateDirEntryInput = {
  path: string;
  name: string;
  /**
   * Determines the display position of this entry among others in the same group.
   * Entries are sorted in ascending order; lower values appear before higher ones.
   * Negative values are allowed and will be placed before positive values.
   * If multiple entries have the same order, they are sorted alphabetically.
   * If not specified, the entry appears last and is sorted alphabetically
   * among unspecified items.
   */
  order: number;
  configuration: DirConfigurationModel;
};

export type CreateEntryInput = { "item": CreateItemEntryInput } | { "dir": CreateDirEntryInput };

export type CreateEntryOutput = { id: string };

export type CreateItemEntryInput = { path: string; name: string; order: number; configuration: ItemConfigurationModel };

export type DeleteEntryInput = { id: string };

export type DeleteEntryOutput = { id: string };

export type StreamEntriesOutput = Record<string, never>;

export type UpdateDirEntryInput = { id: string; path: string; name?: string; order?: number; expanded?: boolean };

export type UpdateDirEntryOutput = { ID: string; PATH: EntryPath; CONFIGURATION: CompositeDirConfigurationModel };

export type UpdateEntryInput = { "ITEM": UpdateItemEntryInput } | { "DIR": UpdateDirEntryInput };

export type UpdateEntryOutput = { "ITEM": UpdateItemEntryOutput } | { "DIR": UpdateDirEntryOutput };

export type UpdateItemEntryInput = {
  id: string;
  path: string;
  name?: string;
  protocol?: EntryProtocol;
  order?: number;
  expanded?: boolean;
};

export type UpdateItemEntryOutput = { ID: string; PATH: EntryPath; CONFIGURATION: CompositeItemConfigurationModel };
