// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EntryPath, EntryProtocol } from "./primitives";
import type {
  CompositeDirConfigurationModel,
  CompositeItemConfigurationModel,
  DirConfigurationModel,
  ItemConfigurationModel,
} from "./types";

export type CreateDirEntryInput = { path: string; name: string; order: number; configuration: DirConfigurationModel };

export type CreateEntryInput = { "item": CreateItemEntryInput } | { "dir": CreateDirEntryInput };

export type CreateEntryOutput = { id: string };

export type CreateItemEntryInput = { path: string; name: string; order: number; configuration: ItemConfigurationModel };

export type DeleteEntryInput = { id: string };

export type DeleteEntryOutput = { id: string };

export type StreamEntriesOutput = Record<string, never>;

export type UpdateDirEntryInput = { id: string; path: string; name?: string; order?: number; expanded?: boolean };

export type UpdateDirEntryOutput = { ID: string; PATH: EntryPath; CONFIGURATION: CompositeDirConfigurationModel };

export type UpdateEntryInput = { "ITEM": UpdateItemEntryInput } | { "DIR": UpdateDirEntryInput };

export type UpdateEntryOutput = { "ITEM": UpdateItemEntryOutput } | { "DIR": UpdateDirEntryOutput };

export type UpdateItemEntryInput = {
  id: string;
  path: string;
  name?: string;
  protocol?: EntryProtocol;
  order?: number;
  expanded?: boolean;
};

export type UpdateItemEntryOutput = { ID: string; PATH: EntryPath; CONFIGURATION: CompositeItemConfigurationModel };
