// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type EntryClass = "Request" | "Endpoint" | "Component" | "Schema";

export type EntryKind = "Dir" | "Item" | "Case";

export type EntryProtocol = "Get" | "Post" | "Put" | "Delete" | "WebSocket" | "Graphql" | "Grpc";

export type WorktreeChange =
  | { "type": "Loaded"; id: string; path: string }
  | { "type": "Created"; id: string; path: string }
  | { "type": "Moved"; id: string; from_id: string; to_id: string; old_path: string; new_path: string }
  | { "type": "Deleted"; id: string; path: string };

export type WorktreeDiff = Array<WorktreeChange>;
