// Generated by ts-to-zod
import { z } from "zod";

export const entryClassSchema = z.union([
  z.literal("Request"),
  z.literal("Endpoint"),
  z.literal("Component"),
  z.literal("Schema"),
]);

export const entryKindSchema = z.union([z.literal("Dir"), z.literal("Item"), z.literal("Case")]);

export const entryPathSchema = z.object({
  raw: z.string(),
  segments: z.array(z.string()),
});

export const entryProtocolSchema = z.union([
  z.literal("Get"),
  z.literal("Post"),
  z.literal("Put"),
  z.literal("Delete"),
  z.literal("WebSocket"),
  z.literal("Graphql"),
  z.literal("Grpc"),
]);

export const httpMethodSchema = z.union([z.literal("GET"), z.literal("POST"), z.literal("PUT"), z.literal("DELETE")]);
