// Generated by ts-to-zod
import { z } from "zod";

export const entryClassSchema = z.union([
  z.literal("Request"),
  z.literal("Endpoint"),
  z.literal("Component"),
  z.literal("Schema"),
]);

export const entryKindSchema = z.union([z.literal("Dir"), z.literal("Item"), z.literal("Case")]);

export const entryProtocolSchema = z.union([
  z.literal("Get"),
  z.literal("Post"),
  z.literal("Put"),
  z.literal("Delete"),
  z.literal("WebSocket"),
  z.literal("Graphql"),
  z.literal("Grpc"),
]);

export const worktreeChangeSchema = z.union([
  z.object({
    "type": z.literal("Loaded"),
    id: z.string(),
    path: z.string(),
  }),
  z.object({
    "type": z.literal("Created"),
    id: z.string(),
    path: z.string(),
  }),
  z.object({
    "type": z.literal("Moved"),
    id: z.string(),
    from_id: z.string(),
    to_id: z.string(),
    old_path: z.string(),
    new_path: z.string(),
  }),
  z.object({
    "type": z.literal("Deleted"),
    id: z.string(),
    path: z.string(),
  }),
]);

export const worktreeDiffSchema = z.array(worktreeChangeSchema);
