// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Classification = "request" | "endpoint" | "component" | "schema";

export type EntryId = number;

export type EntryInfo = {
  id: EntryId;
  name: string;
  path: string;
  isDir: boolean;
  classification: Classification;
  protocol?: RequestProtocol;
  order?: number;
};

export type EntryKind = "dir" | "file";

export type EnvironmentInfo = { id: string; name: string; order?: number };

export type FormDataItem = {
  key: string;
  value: FormDataValue;
  order?: number;
  desc?: string;
  disabled: boolean;
  options: FormDataOptions;
};

export type FormDataOptions = { propagate: boolean };

export type FormDataValue = { "text": string } | { "file": string };

export type HeaderParamItem = {
  key: string;
  value: string;
  order?: number;
  desc?: string;
  disabled: boolean;
  options: HeaderParamOptions;
};

export type HeaderParamOptions = { propagate: boolean };

export type HttpMethod = "post" | "get" | "put" | "delete";

export type PathChangeKind = "loaded" | "created" | "removed" | "updated";

export type PathParamItem = {
  key: string;
  value: string;
  order?: number;
  desc?: string;
  disabled: boolean;
  options: PathParamOptions;
};

export type PathParamOptions = { propagate: boolean };

export type QueryParamItem = {
  key: string;
  value: string;
  order?: number;
  desc?: string;
  disabled: boolean;
  options: QueryParamOptions;
};

export type QueryParamOptions = { propagate: boolean };

export type RawBodyType = { "text": string } | { "json": string } | { "html": string } | { "xml": string };

export type RequestBody =
  | { "raw": RawBodyType }
  | { "formData": Array<FormDataItem> }
  | { "urlEncoded": Array<UrlEncodedItem> }
  | { "binary": string };

export type RequestProtocol = { "http": HttpMethod } | "webSocket" | "graphQL" | "grpc";

export type UrlEncodedItem = {
  key: string;
  value: string;
  order?: number;
  desc?: string;
  disabled: boolean;
  options: UrlEncodedOptions;
};

export type UrlEncodedOptions = { propagate: boolean };
