// Generated by ts-to-zod
import { z } from "zod";
import { entryClassSchema, entryKindSchema, entryProtocolSchema, httpMethodSchema } from "./primitives.zod";

export const componentDirConfigurationModelSchema = z.never();

export const componentItemConfigurationModelSchema = z.never();

export const configurationMetadataSchema = z.object({
  id: z.string(),
});

export const endpointDirConfigurationModelSchema = z.never();

export const schemaDirConfigurationModelSchema = z.never();

export const endpointItemConfigurationModelSchema = z.never();

export const environmentInfoSchema = z.object({
  id: z.string(),
  name: z.string(),
  order: z.number().optional(),
});

export const formDataValueSchema = z.union([
  z.object({
    "text": z.string(),
  }),
  z.object({
    "file": z.string(),
  }),
]);

export const formDataOptionsSchema = z.object({
  propagate: z.boolean(),
});

export const headerParamOptionsSchema = z.object({
  propagate: z.boolean(),
});

export const httpDirConfigurationModelSchema = z.record(z.never());

export const schemaItemConfigurationModelSchema = z.never();

export const pathParamOptionsSchema = z.object({
  propagate: z.boolean(),
});

export const queryParamOptionsSchema = z.object({
  propagate: z.boolean(),
});

export const rawBodyTypeSchema = z.union([
  z.object({
    "text": z.string(),
  }),
  z.object({
    "json": z.string(),
  }),
  z.object({
    "html": z.string(),
  }),
  z.object({
    "xml": z.string(),
  }),
]);

export const formDataItemSchema = z.object({
  key: z.string(),
  value: formDataValueSchema,
  order: z.number().optional(),
  desc: z.string().optional(),
  disabled: z.boolean(),
  options: formDataOptionsSchema,
});

export const requestDirConfigurationModelSchema = z.object({
  "http": httpDirConfigurationModelSchema,
});

export const urlEncodedOptionsSchema = z.object({
  propagate: z.boolean(),
});
export const dirConfigurationModelSchema = z.union([
  z.object({
    "request": requestDirConfigurationModelSchema,
  }),
  z.object({
    "endpoint": endpointDirConfigurationModelSchema,
  }),
  z.object({
    "component": componentDirConfigurationModelSchema,
  }),
  z.object({
    "schema": schemaDirConfigurationModelSchema,
  }),
]);

export const entryInfoSchema = z.object({
  id: z.string(),
  name: z.string(),
  path: z.string(),
  class: entryClassSchema,
  kind: entryKindSchema,
  protocol: entryProtocolSchema.optional(),
  order: z.number().optional(),
  expanded: z.boolean(),
});

export const headerParamItemSchema = z.object({
  key: z.string(),
  value: z.string(),
  order: z.number().optional(),
  desc: z.string().optional(),
  disabled: z.boolean(),
  options: headerParamOptionsSchema,
});

export const httpRequestPartsSchema = z.object({
  method: httpMethodSchema,
});

export const pathParamItemSchema = z.object({
  key: z.string(),
  value: z.string(),
  order: z.number().optional(),
  desc: z.string().optional(),
  disabled: z.boolean(),
  options: pathParamOptionsSchema,
});

export const queryParamItemSchema = z.object({
  key: z.string(),
  value: z.string(),
  order: z.number().optional(),
  desc: z.string().optional(),
  disabled: z.boolean(),
  options: queryParamOptionsSchema,
});

export const urlEncodedItemSchema = z.object({
  key: z.string(),
  value: z.string(),
  order: z.number().optional(),
  desc: z.string().optional(),
  disabled: z.boolean(),
  options: urlEncodedOptionsSchema,
});

export const httpRequestItemConfigurationSchema = z.object({
  requestParts: httpRequestPartsSchema,
});

export const requestItemConfigurationModelSchema = z.object({
  "http": httpRequestItemConfigurationSchema,
});

export const requestBodySchema = z.union([
  z.object({
    "raw": rawBodyTypeSchema,
  }),
  z.object({
    "formData": z.array(formDataItemSchema),
  }),
  z.object({
    "urlEncoded": z.array(urlEncodedItemSchema),
  }),
  z.object({
    "binary": z.string(),
  }),
]);

export const itemConfigurationModelSchema = z.union([
  z.object({
    "request": requestItemConfigurationModelSchema,
  }),
  z.object({
    "endpoint": endpointItemConfigurationModelSchema,
  }),
  z.object({
    "component": componentItemConfigurationModelSchema,
  }),
  z.object({
    "schema": schemaItemConfigurationModelSchema,
  }),
]);
