// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LanguageDirection } from "./primitives";

/**
 * @category Type
 */
export type LanguageInfo = { displayName: string; code: string; direction?: LanguageDirection };

/**
 * A structure representing a localized string with a key and original text.
 *
 * The `key` field serves as a unique identifier for the localization entry, while `origin`
 * is the fallback or original text.
 *
 * # Example
 *
 * ```rust
 * use base::localize;
 *
 * // Using the `localize!` macro for concise creation
 * let welcome = localize!("welcome.message", "Welcome!");
 * ```
 */
export type LocalizedString = {
  /**
   * The unique key identifying the localized string.
   */
  key: string;
  /**
   * The fallback string associated with the key, used when the key is not found.
   */
  fallback: string;
};
