// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LanguageDirection } from "./primitives";

/**
 * @category Type
 */
export type LanguageInfo = { displayName: string; code: string; direction?: LanguageDirection };
