// Generated by ts-to-zod
import { z } from "zod";
import { languageDirectionSchema } from "./primitives.zod";

export const localizedStringSchema = z.object({
  key: z.string(),
  fallback: z.string(),
});
export const languageInfoSchema = z.object({
  displayName: z.string(),
  code: z.string(),
  direction: languageDirectionSchema.optional(),
});
