[package]
name = "xtask"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
toml = "0.9.4"
cargo_metadata = "0.21"
pathdiff = "0.2"
futures = "0.3.31"
smol = "2.0.2"
clap = { version = "4.5.28", features = ["derive"] }

tokio = { workspace = true, features = ["full"] }
serde = { workspace = true, features = ["derive"] }

anyhow.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
tracing-appender.workspace = true
toml_edit.workspace = true
