// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LogDate, LogLevel } from "./types";

export type ListLogsInput = {
  dates: Array<LogDate>;
  levels: Array<LogLevel>;
  CollectionPath?: string;
  RequestPath?: string;
};

export type ListLogsOutput = { contents: Array<LogEntry> };

export type LogEntry = { timestamp: string; level: string; request?: string; collection?: string; message: string };
