// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LogDate, LogLevel } from "./types";

export type ListLogsInput = { dates: Array<LogDate>; levels: Array<LogLevel>; resource?: string };

export type ListLogsOutput = { contents: Array<LogEntry> };

export type LogEntry = { id: string; timestamp: string; level: string; resource?: string; message: string };
