// Generated by ts-to-zod
import { z } from "zod";
import { logDateSchema, logLevelSchema } from "./types.zod";

export const logEntrySchema = z.object({
  timestamp: z.string(),
  level: z.string(),
  request: z.string().optional(),
  collection: z.string().optional(),
  message: z.string(),
});
export const listLogsInputSchema = z.object({
  dates: z.array(logDateSchema),
  levels: z.array(logLevelSchema),
  resource: z.string().nullable(),
});

export const listLogsOutputSchema = z.object({
  contents: z.array(logEntrySchema),
});
