// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LogDate, LogLevel } from "./types";

export type DeleteLogInput = { timestamp: string; id: string };

export type DeleteLogOutput = { id: string };

export type DeleteLogsInput = { entries: Array<DeleteLogInput> };

export type DeleteLogsOutput = { deletedEntries: Array<DeleteLogOutput> };

export type ListLogsInput = { dates: Array<LogDate>; levels: Array<LogLevel>; resource?: string };

export type ListLogsOutput = { contents: Array<LogEntryInfo> };

export type LogEntryInfo = {
  id: string;
  /**
   * A timestamp string, such as "2025-06-06T19:26:39.084+0300"
   */
  timestamp: string;
  level: LogLevel;
  resource?: string;
  message: string;
};
