// Generated by ts-to-zod
import { z } from "zod";

export const logDateSchema = z.object({
  year: z.number(),
  month: z.number(),
  day: z.number(),
});

export const logLevelSchema = z.union([
  z.literal("TRACE"),
  z.literal("DEBUG"),
  z.literal("INFO"),
  z.literal("WARN"),
  z.literal("ERROR"),
]);
