// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type LogDate = { year: number; month: number; day: number };

export type LogLevel = "TRACE" | "DEBUG" | "INFO" | "WARN" | "ERROR";
