// Generated by ts-to-zod
import { jsonValueSchema } from "@repo/bindings-utils";
import { z } from "zod";

export const changeStringSchema = z.union([
  z.object({
    "UPDATE": z.string(),
  }),
  z.literal("REMOVE"),
]);
export const changeJsonValueSchema = z.union([
  z.object({
    "UPDATE": jsonValueSchema,
  }),
  z.literal("REMOVE"),
]);
