// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

import { JsonValue } from "@repo/bindings-utils";

export type ChangeJsonValue = { "UPDATE": JsonValue } | "REMOVE";

/**
 * @category Primitive
 */
export type ChangeString = { "UPDATE": string } | "REMOVE";
