// Generated by ts-to-zod
import { changeJsonValueSchema, changeStringSchema, jsonValueSchema } from "@repo/moss-bindingutils";
import { z } from "zod";

export const variableOptionsSchema = z.object({
  disabled: z.boolean(),
});

export const variableKindSchema = z.union([z.literal("secret"), z.literal("default")]);
export const addVariableParamsSchema = z.object({
  name: z.string(),
  globalValue: jsonValueSchema,
  localValue: jsonValueSchema,
  order: z.number(),
  desc: z.string().optional(),
  options: variableOptionsSchema,
});

export const updateVariableParamsSchema = z.object({
  id: z.string(),
  name: z.string().optional(),
  globalValue: changeJsonValueSchema.optional(),
  localValue: changeJsonValueSchema.optional(),
  order: z.number().optional(),
  desc: changeStringSchema.optional(),
});

export const variableInfoSchema = z.object({
  id: z.string(),
  name: z.string(),
  globalValue: jsonValueSchema.optional(),
  localValue: jsonValueSchema.optional(),
  disabled: z.boolean(),
  order: z.number(),
  desc: z.string().optional(),
});
