// @ts-nocheck - File uses recursive schemas that may cause "Type instantiation is excessively deep" errors
// Generated by ts-to-zod
import { changeJsonValueSchema, changeStringSchema, jsonValueSchema } from "@repo/moss-bindingutils";
import { z } from "zod";

export const variableOptionsSchema = z.object({
  disabled: z.boolean(),
});
export const addVariableParamsSchema = z.object({
  name: z.string(),
  globalValue: jsonValueSchema,
  localValue: jsonValueSchema,
  order: z.number(),
  desc: z.string().optional(),
  options: variableOptionsSchema,
});

export const updateVariableParamsSchema = z.object({
  id: z.string(),
  name: z.string().optional(),
  globalValue: changeJsonValueSchema.optional(),
  localValue: changeJsonValueSchema.optional(),
  order: z.number().optional(),
  desc: changeStringSchema.optional(),
  options: variableOptionsSchema.optional(),
});
