// Generated by ts-to-zod
import { z } from "zod";

export const variableValueSchema = z.union([z.string(), z.number(), z.boolean()]);

export const variableKindSchema = z.union([z.literal("secret"), z.literal("default")]);

export const variableInfoSchema = z.object({
  name: z.string(),
  globalValue: variableValueSchema.optional(),
  localValue: variableValueSchema.optional(),
  disabled: z.boolean(),
  kind: variableKindSchema,
  order: z.number().optional(),
  desc: z.string().optional(),
});
