// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import { JsonValue } from "@repo/bindings-utils";
import type { ChangeJsonValue, ChangeString } from "./primitives";

export type AddVariableParams = {
  name: string;
  globalValue: JsonValue;
  localValue: JsonValue;
  order: number;
  desc?: string;
  options: VariableOptions;
};

export type UpdateVariableParams = {
  name?: string;
  globalValue?: ChangeJsonValue;
  localValue?: ChangeJsonValue;
  order?: number;
  desc?: ChangeString;
};

/**
 * @category Type
 */
export type VariableInfo = {
  id: string;
  name: string;
  globalValue: JsonValue;
  localValue: JsonValue;
  disabled: boolean;
  order: number;
  desc?: string;
};

/**
 * @category Type
 */
export type VariableKind = "secret" | "default";

export type VariableOptions = { disabled: boolean };
