// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

import { ChangeJsonValue, ChangeString, JsonValue } from "@repo/moss-bindingutils";

/**
 * @category Type
 */
export type AddVariableParams = {
  name: string;
  globalValue: JsonValue;
  localValue: JsonValue;
  order: number;
  desc?: string;
  options: VariableOptions;
};

/**
 * @category Type
 */
export type UpdateVariableParams = {
  id: string;
  name?: string;
  globalValue?: ChangeJsonValue;
  localValue?: ChangeJsonValue;
  order?: number;
  desc?: ChangeString;
};

/**
 * @category Type
 */
export type VariableInfo = {
  id: string;
  name: string;
  globalValue?: JsonValue;
  localValue?: JsonValue;
  disabled: boolean;
  order: number;
  desc?: string;
};

/**
 * @category Type
 */
export type VariableKind = "secret" | "default";

/**
 * @category Type
 */
export type VariableOptions = { disabled: boolean };
