// FIXME: remove mock log resources
const today = new Date().toISOString().split("T")[0];

export const testLogResources = [
  { timestamp: `${today} 08:12:34`, level: "INFO", service: "ApiService", message: "Server started on port 3000" },
  {
    timestamp: `${today} 08:12:35`,
    level: "INFO",
    service: "DatabaseConnector",
    message: "Successfully connected to database",
  },
  {
    timestamp: `${today} 08:12:36`,
    level: "DEBUG",
    service: "AuthController",
    message: "User authentication middleware initialized",
  },
  {
    timestamp: `${today} 08:13:01`,
    level: "INFO",
    service: "UserService",
    message: "User profile updated: userId=12345",
  },
  {
    timestamp: `${today} 08:13:42`,
    level: "WARNING",
    service: "CacheService",
    message: "Cache invalidation taking longer than expected",
  },
  {
    timestamp: `${today} 08:14:15`,
    level: "ERROR",
    service: "FileService",
    message: "Failed to write file: permission denied",
  },
  { timestamp: `${today} 08:14:22`, level: "INFO", service: "ApiService", message: "GET /api/users - 200 OK - 15ms" },
  {
    timestamp: `${today} 08:14:23`,
    level: "INFO",
    service: "ApiService",
    message: "GET /api/products - 200 OK - 28ms",
  },
  {
    timestamp: `${today} 08:14:25`,
    level: "DEBUG",
    service: "ProductController",
    message: "Filtering products by category: electronics",
  },
  {
    timestamp: `${today} 08:15:01`,
    level: "INFO",
    service: "ApiService",
    message: "POST /api/orders - 201 Created - 54ms",
  },
  {
    timestamp: `${today} 08:15:12`,
    level: "WARNING",
    service: "PaymentService",
    message: "Payment gateway response delayed: transaction=T78912345",
  },
  {
    timestamp: `${today} 08:15:30`,
    level: "ERROR",
    service: "NotificationService",
    message: "Failed to send email notification: SMTP connection refused",
  },
  {
    timestamp: `${today} 08:16:11`,
    level: "INFO",
    service: "UserService",
    message: "New user registered: userId=12346",
  },
  {
    timestamp: `${today} 08:16:45`,
    level: "DEBUG",
    service: "SecurityService",
    message: "Rate limit applied to IP: 192.168.1.254",
  },
  {
    timestamp: `${today} 08:17:03`,
    level: "INFO",
    service: "ApiService",
    message: "GET /api/dashboard/stats - 200 OK - 135ms",
  },
  {
    timestamp: `${today} 08:17:33`,
    level: "ERROR",
    service: "DatabaseConnector",
    message: "Query timeout after 5000ms: SELECT * FROM transactions WHERE date > '2023-01-01'",
  },
  { timestamp: `${today} 08:18:05`, level: "INFO", service: "CacheService", message: "Cache hit ratio: 78.5%" },
  {
    timestamp: `${today} 08:18:22`,
    level: "DEBUG",
    service: "SearchService",
    message: "Building search index for products",
  },
  {
    timestamp: `${today} 08:19:14`,
    level: "WARNING",
    service: "ApiService",
    message: "Endpoint /api/reports/generate is deprecated and will be removed in v2.5",
  },
  {
    timestamp: `${today} 08:19:51`,
    level: "INFO",
    service: "BackupService",
    message: "Daily backup completed successfully in 45s",
  },
  {
    timestamp: `${today} 08:20:05`,
    level: "ERROR",
    service: "AuthController",
    message: "Too many failed login attempts for user: admin@example.com",
  },
  {
    timestamp: `${today} 08:20:30`,
    level: "INFO",
    service: "ApiService",
    message: "GET /api/settings - 200 OK - 18ms",
  },
  {
    timestamp: `${today} 08:21:12`,
    level: "DEBUG",
    service: "ConfigService",
    message: "Loading configuration from environment variables",
  },
  {
    timestamp: `${today} 08:21:45`,
    level: "INFO",
    service: "SchedulerService",
    message: "Scheduled task 'cleanTempFiles' started",
  },
  {
    timestamp: `${today} 08:22:01`,
    level: "WARNING",
    service: "MemoryMonitor",
    message: "High memory usage detected: 85% of allocated heap",
  },
  {
    timestamp: `${today} 08:22:33`,
    level: "INFO",
    service: "ApiService",
    message: "PUT /api/users/12345 - 200 OK - 42ms",
  },
  {
    timestamp: `${today} 08:23:17`,
    level: "DEBUG",
    service: "RenderingEngine",
    message: "Precompiling templates for faster rendering",
  },
  {
    timestamp: `${today} 08:24:02`,
    level: "ERROR",
    service: "NetworkService",
    message: "Connection to external API failed after 3 retries: https://api.external-service.com",
  },
  {
    timestamp: `${today} 08:24:33`,
    level: "INFO",
    service: "SchedulerService",
    message: "Scheduled task 'cleanTempFiles' completed in 168s",
  },
  {
    timestamp: `${today} 08:25:00`,
    level: "INFO",
    service: "ApiService",
    message: "GET /api/analytics/reports - 200 OK - 213ms",
  },
];
