// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ColorThemeDescriptor } from "./types";

export type GetColorThemeInput = { id: string };

export type GetColorThemeOutput = { cssContent: string };

export type ListColorThemesOutput = Array<ColorThemeDescriptor>;
