// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
export type GetColorThemeInput = { id: string };

export type GetColorThemeOutput = { cssContent: string };

import type { ColorThemeInfo } from "./types";

export type ListColorThemesOutput = Array<ColorThemeInfo>;
