// Generated by ts-to-zod
import { z } from "zod";
import { colorThemeInfoSchema } from "./types.zod";

export const getColorThemeInputSchema = z.object({
  id: z.string(),
});

export const getColorThemeOutputSchema = z.object({
  cssContent: z.string(),
});
export const listColorThemesOutputSchema = z.array(colorThemeInfoSchema);
