// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * @category Primitive
 */
export type ThemeId = string;

/**
 * @category Primitive
 */
export type ThemeMode = "light" | "dark";
