// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ThemeDescriptor = { identifier: string, displayName: string, order: number, path: string, isDefault: boolean, };
