// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ColorThemeInfo = {
  identifier: string;
  displayName: string;
  mode: ThemeMode;
  order?: number;
  source: string;
  isDefault?: boolean;
};

export type ThemeMode = "light" | "dark";
