// Generated by ts-to-zod
import { z } from "zod";

export const themeModeSchema = z.union([z.literal("light"), z.literal("dark")]);

export const colorThemeInfoSchema = z.object({
  identifier: z.string(),
  displayName: z.string(),
  mode: themeModeSchema,
  order: z.number().optional(),
  source: z.string(),
  isDefault: z.boolean().optional(),
});
