// Generated by ts-to-zod
import { z } from "zod";
import { themeModeSchema } from "./primitives.zod";

export const cssValueSchema = z.union([
  z.object({
    "type": z.literal("String"),
    value: z.string(),
  }),
  z.object({
    "type": z.literal("Variable"),
    value: z.string(),
  }),
]);
export const themeSchema = z.object({
  identifier: z.string(),
  displayName: z.string(),
  mode: themeModeSchema,
  tokens: z.record(z.string(), cssValueSchema),
});
