// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ThemeMode } from "./primitives";

/**
 * @category Primitive
 */
export type CssValue = { "type": "String"; value: string } | { "type": "Variable"; value: string };

/**
 * @category Type
 */
export type Theme = { identifier: string; displayName: string; mode: ThemeMode; tokens: Record<string, CssValue> };
