// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * DEPRECATED
 * @category Operation
 */
export type OpenWorkspaceOutput = { id: string };

/**
 * @category Operation
 */
export type WelcomeWindow_CreateWorkspaceInput = { name: string };

/**
 * @category Operation
 */
export type WelcomeWindow_CreateWorkspaceOutput = { id: string };

/**
 * @category Operation
 */
export type WelcomeWindow_OpenWorkspaceInput = { id: string };

/**
 * @category Operation
 *
 * Used for updating any workspace from any window.
 */
export type WelcomeWindow_UpdateWorkspaceInput = {
  id: string;
  /**
   * A new name for the workspace, if provided, the workspace
   * will be renamed to this name.
   */
  name?: string;
};

/**
 * @category Operation
 */
export type WelcomeWindow_UpdateWorkspaceOutput = Record<string, never>;
