// Generated by ts-to-zod
import { z } from "zod";

export const openWorkspaceOutputSchema = z.object({
  id: z.string(),
});

export const welcomeWindowCreateWorkspaceInputSchema = z.object({
  name: z.string(),
});

export const welcomeWindowCreateWorkspaceOutputSchema = z.object({
  id: z.string(),
});

export const welcomeWindowOpenWorkspaceInputSchema = z.object({
  id: z.string(),
});

export const welcomeWindowUpdateWorkspaceInputSchema = z.object({
  id: z.string(),
  name: z.string().optional(),
});

export const welcomeWindowUpdateWorkspaceOutputSchema = z.record(z.string(), z.never());
