// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * @category Operation
 */
export type WelcomeWindow_CreateWorkspaceInput = { name: string };

/**
 * @category Operation
 */
export type WelcomeWindow_CreateWorkspaceOutput = { id: string };
