// Generated by ts-to-zod
import { z } from "zod";

export const welcomeWindowCreateWorkspaceInputSchema = z.object({
  name: z.string(),
});

export const welcomeWindowCreateWorkspaceOutputSchema = z.object({
  id: z.string(),
});
