[package]
name = "moss_tauri"
version = "0.1.0"
edition = "2024"

[dependencies]
moss_common.workspace = true

thiserror.workspace = true
anyhow.workspace = true
serde.workspace = true
serde_json.workspace = true
