[package]
name = "moss_tauri"
version = "0.1.0"
edition = "2024"

[dependencies]
moss_app.workspace = true
moss_common.workspace = true

anyhow.workspace = true
serde.workspace = true
serde_json.workspace = true
