// Generated by ts-to-zod
import { z } from "zod";
import { themeIdSchema, themeModeSchema } from "./primitives.zod";
export const colorThemeInfoSchema = z.object({
  identifier: themeIdSchema,
  displayName: z.string(),
  mode: themeModeSchema,
  source: z.string(),
});
