// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

import { ThemeId, ThemeMode } from "./primitives";

/**
 * @category Type
 */
export type ColorThemeInfo = {
  identifier: ThemeId;
  displayName: string;
  mode: ThemeMode;
  order?: number;
  source: string;
  isDefault?: boolean;
};
