// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ExtensionInfo = {
  id: string;
  externalId: string;
  name: string;
  authors: Array<string>;
  description: string;
  repository: string;
  downloads: bigint;
  createdAt: string;
  updatedAt: string;
  latestVersion: string;
};

export type ExtensionVersionInfo = {
  id: string;
  externalId: string;
  name: string;
  authors: Array<string>;
  description: string;
  repository: string;
  downloads: bigint;
  createdAt: string;
  updatedAt: string;
  version: string;
};
