// Generated by ts-to-zod
import { z } from "zod";

import { type JsonValue } from "./serde_json";

export const jsonValueSchema: z.ZodSchema<JsonValue> = z.lazy(() =>
  z.union([z.number(), z.string(), z.boolean(), z.array(jsonValueSchema), z.any()]).nullable()
);
